import Cortex.Graph.Core
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Finset.Prod

/-!
## Overview

Extensional denotation for Mokhov graphs.

## Context

`Cortex.Graph.Core` defines the free syntax tree generated by
`empty`, `vertex`, `overlay`, and `connect`. The algebraic laws do not
hold by definitional equality on that tree. They do hold for the
standard relation denotation: a finite vertex set plus a finite edge
set, with `connect` adding every cross edge from the left vertex set to
the right vertex set.

This module is phase 1 of the quotient story. It proves the laws on the
denotation. A later `Cortex.Graph.Quotient` module can use this as the
semantic model for lifting the laws back to graph equivalence.

## Theorem Split

The page first defines finite relation operations, then proves Mokhov's
laws extensionally, and finally connects the AST syntax to the relation
model through `denote`.
-/

namespace Cortex.Graph

/-! ## Relation Model -/

/-- `Relation α` is the concrete finite graph model: vertices plus directed edges. -/
structure Relation (α : Type) where
  vertices : Finset α
  edges : Finset (α × α)
  deriving DecidableEq

namespace Relation

variable {α : Type}

@[ext]
theorem ext {r s : Relation α}
    (h_vertices : r.vertices = s.vertices)
    (h_edges : r.edges = s.edges) :
    r = s := by
  cases r with
  | mk rVertices rEdges =>
      cases s with
      | mk sVertices sEdges =>
          cases h_vertices
          cases h_edges
          rfl

variable [DecidableEq α]

/-- `empty` is the relation with no vertices and no edges. -/
def empty : Relation α :=
  { vertices := ∅, edges := ∅ }

/-- `vertex v` is the relation with one vertex and no edges. -/
def vertex (v : α) : Relation α :=
  { vertices := {v}, edges := ∅ }

/-- `overlay r s` unions the vertex sets and edge sets. -/
def overlay (r s : Relation α) : Relation α :=
  { vertices := r.vertices ∪ s.vertices
  , edges := r.edges ∪ s.edges
  }

/-- `cross left right` is every directed edge from a left vertex to a right vertex. -/
def cross (left right : Finset α) : Finset (α × α) :=
  left ×ˢ right

/-- `connect r s` overlays two relations and adds every cross edge from `r` to `s`. -/
def connect (r s : Relation α) : Relation α :=
  { vertices := r.vertices ∪ s.vertices
  , edges := r.edges ∪ s.edges ∪ cross r.vertices s.vertices
  }

/-! ## Mokhov Laws in the Relation Denotation -/

@[simp]
theorem overlay_empty_left (r : Relation α) :
    overlay empty r = r := by
  ext x <;> simp [overlay, empty]

@[simp]
theorem overlay_empty_right (r : Relation α) :
    overlay r empty = r := by
  ext x <;> simp [overlay, empty]

theorem overlay_comm (r s : Relation α) :
    overlay r s = overlay s r := by
  ext x <;> simp [overlay, Finset.union_comm]

theorem overlay_assoc (r s t : Relation α) :
    overlay (overlay r s) t = overlay r (overlay s t) := by
  ext x <;> simp [overlay, Finset.union_assoc]

@[simp]
theorem connect_empty_left (r : Relation α) :
    connect empty r = r := by
  ext x <;> simp [connect, empty, cross]

@[simp]
theorem connect_empty_right (r : Relation α) :
    connect r empty = r := by
  ext x <;> simp [connect, empty, cross]

theorem connect_assoc (r s t : Relation α) :
    connect (connect r s) t = connect r (connect s t) := by
  ext x
  · simp [connect]
  · simp [connect, cross, Finset.mem_product]
    tauto

theorem connect_distrib_overlay_left (r s t : Relation α) :
    connect r (overlay s t) =
      overlay (connect r s) (connect r t) := by
  ext x <;>
    simp [connect, overlay, cross, Finset.mem_product] <;>
    tauto

theorem connect_distrib_overlay_right (r s t : Relation α) :
    connect (overlay r s) t =
      overlay (connect r t) (connect s t) := by
  ext x <;>
    simp [connect, overlay, cross, Finset.mem_product] <;>
    tauto

/-- `connect_decomposition` proves Mokhov's decomposition law in the relation denotation. -/
theorem connect_decomposition (r s t : Relation α) :
    connect (connect r s) t =
      overlay (overlay (connect r s) (connect r t)) (connect s t) := by
  ext x <;>
    simp [connect, overlay, cross, Finset.mem_product] <;>
    tauto

end Relation

/-! ## AST Denotation -/

variable {α : Type} [DecidableEq α]

/-- `denote g` interprets a Mokhov graph expression as a finite relation. -/
def denote : Graph α → Relation α
  | Graph.empty => Relation.empty
  | Graph.vertex v => Relation.vertex v
  | Graph.overlay g h => Relation.overlay (denote g) (denote h)
  | Graph.connect g h => Relation.connect (denote g) (denote h)

@[simp]
theorem denote_empty :
    denote (α := α) Graph.empty = Relation.empty := rfl

@[simp]
theorem denote_vertex (v : α) :
    denote (Graph.vertex v) = Relation.vertex v := rfl

@[simp]
theorem denote_overlay (g h : Graph α) :
    denote (Graph.overlay g h) = Relation.overlay (denote g) (denote h) := rfl

@[simp]
theorem denote_connect (g h : Graph α) :
    denote (Graph.connect g h) = Relation.connect (denote g) (denote h) := rfl

theorem denote_overlay_comm (g h : Graph α) :
    denote (Graph.overlay g h) = denote (Graph.overlay h g) :=
  Relation.overlay_comm (denote g) (denote h)

theorem denote_connect_decomposition (g h k : Graph α) :
    denote (Graph.connect (Graph.connect g h) k) =
      denote
        (Graph.overlay
          (Graph.overlay (Graph.connect g h) (Graph.connect g k))
          (Graph.connect h k)) :=
  Relation.connect_decomposition (denote g) (denote h) (denote k)

end Cortex.Graph
