// Node entrypoint for tree-sitter-wire.
// Loads the prebuilt binding via node-gyp-build, falling back gracefully if
// node-types.json is not available (e.g. during early build).

const root = require("path").join(__dirname, "..", "..");

module.exports = require("node-gyp-build")(root);

try {
  module.exports.nodeTypeInfo = require("../../src/node-types.json");
} catch (_) {
  // node-types.json is generated by `tree-sitter generate` and checked into
  // src/. If absent (e.g. stale checkout), downstream consumers that don't
  // rely on typeInfo still work.
}
