import Cortex.Wire.ContractValidation.Emitted.SubsetAccept
import Cortex.Wire.ContractValidation.Emitted.RequiredNested
import Cortex.Wire.ContractValidation.Emitted.AdditionalProperties
import Cortex.Wire.ContractValidation.Emitted.EnumMismatch
import Cortex.Wire.ContractValidation.Emitted.ItemsElement
import Cortex.Wire.ContractValidation.Emitted.StringBounds
import Cortex.Wire.ContractValidation.Emitted.NumberBounds
import Cortex.Wire.ContractValidation.Emitted.IntegerScalar
import Cortex.Wire.ContractValidation.Emitted.TypeUnion
import Cortex.Wire.ContractValidation.Emitted.EmptyEnum
import Cortex.Wire.ContractValidation.Emitted.EmptyTypes
import Cortex.Wire.ContractValidation.Emitted.BoundsVacuity
import Cortex.Wire.ContractValidation.Emitted.ItemsVacuity
import Cortex.Wire.ContractValidation.Emitted.AdditionalTrue
import Cortex.Wire.ContractValidation.Emitted.RequiredVacuity

/-!
## Overview

Umbrella for the generated contract-schema dialect fixtures. Each import
is a Lean module generated by `Cortex.Wire.LeanFixture`; regenerate with
`just wire-lean-fixtures`. The Haskell test suite fails when any
generated module drifts from the current renderer output.
-/

-- Dialect version pin: mirrors `wireContractDialectVersion` in
-- `src/Cortex/Wire/ContractValidation.hs`. A one-sided bump regenerates
-- this umbrella; the build then fails until the Lean constant follows.
#guard Cortex.Wire.ContractValidation.dialectVersion == 1
