import Cortex.Wire.ElaborationIRDecide
import Cortex.Wire.GraphElaborationExec
import Mathlib.Tactic.FinCases

/-!
## Overview

Differential oracle for the `Make` fixture: the
executable admission kernel replays the compiler's composition (reconstructed
from the emitted artifact's primitive trace, binding annotations skipped)
against a module shell assembled from the artifact's node rows, and must land
on the exposed boundary the compiler recorded.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures`; the Haskell test suite fails on drift.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace DifferentialMake

open Cortex.Wire.ElaborationIR

/-- Declared contract `Sample` (closure row; fields are not modeled). -/
def contract0 : AcceptedRecordContractDecl where
  contract := ⟨"Sample"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Accepted declaration for node `workers_0`. -/
def node0 : AcceptedNodeDecl where
  node := ⟨"workers_0"⟩
  nodeValid := by decide
  inputs := ∅
  outputs := [.single ⟨⟨"workers_0"⟩, ⟨"Sample"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `workers_1`. -/
def node1 : AcceptedNodeDecl where
  node := ⟨"workers_1"⟩
  nodeValid := by decide
  inputs := ∅
  outputs := [.single ⟨⟨"workers_1"⟩, ⟨"Sample"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `workers_2`. -/
def node2 : AcceptedNodeDecl where
  node := ⟨"workers_2"⟩
  nodeValid := by decide
  inputs := ∅
  outputs := [.single ⟨⟨"workers_2"⟩, ⟨"Sample"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Module shell assembled from the artifact's node rows. -/
def shell : AdmittedModuleShell where
  contracts := [contract0]
  contractsUnique := by decide
  kinds := []
  kindsUnique := by decide
  nodes := [node0, node1, node2]
  nodesUnique := by decide
  graphs := []
  graphsUnique := by decide
  graphsValid := fun _ hGraph => nomatch hGraph
  recordFieldContractsClosed := by
    intro contract hContract
    fin_cases hContract <;> exact fun _ hField => nomatch hField
  nodeContractsClosed := by
    intro node hNode
    fin_cases hNode <;>
      refine ⟨fun port hPort => ?_, fun port hPort => ?_⟩ <;>
        fin_cases hPort <;>
          exact ContractId.ClosedBy.declared (by decide)
  kindContractsClosed := fun _ hKind => nomatch hKind
  graphRefsClosed := fun _ hGraph => nomatch hGraph

/-- Core expression reconstructed from the artifact's primitive trace
(binding annotations skipped; the differential is frontier-level). -/
def expr : GraphExpr :=
  .overlay (.overlay (.node ⟨"workers_0"⟩) (.node ⟨"workers_1"⟩)) (.node ⟨"workers_2"⟩)

/-- Output frontier the compiler exposed for this fixture. -/
def expectedOutputs : Finset (SourcePortInstance NodeId OutputPortSignature) :=
  { ⟨⟨"workers_0"⟩, ⟨⟨⟨"workers_0"⟩, ⟨"Sample"⟩⟩⟩⟩
  , ⟨⟨"workers_1"⟩, ⟨⟨⟨"workers_1"⟩, ⟨"Sample"⟩⟩⟩⟩
  , ⟨⟨"workers_2"⟩, ⟨⟨⟨"workers_2"⟩, ⟨"Sample"⟩⟩⟩⟩
  }

/-- Input frontier the compiler exposed for this fixture. -/
def expectedInputs : Finset (SourcePortInstance NodeId InputPortSignature) := ∅

-- The kernel replays the compiler's composition onto the same boundary.
#guard
  match CertifiedGraph.elaborate shell expr with
  | .ok result =>
      decide (result.val.object.graph.exposedOutputs = expectedOutputs) &&
        decide (result.val.object.graph.exposedInputs = expectedInputs)
  | .error _ => false

end DifferentialMake
end AdmissionArtifact
end Cortex.Wire
