import Cortex.Wire.ElaborationIRDecide
import Cortex.Wire.GraphElaborationExec
import Mathlib.Tactic.FinCases

/-!
## Overview

Differential oracle for the `MakeEach` fixture: the
executable admission kernel replays the compiler's composition (reconstructed
from the emitted artifact's primitive trace, binding annotations skipped)
against a module shell assembled from the artifact's node rows, and must land
on the exposed boundary the compiler recorded.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures`; the Haskell test suite fails on drift.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace DifferentialMakeEach

open Cortex.Wire.ElaborationIR

/-- Declared contract `Sample` (closure row; fields are not modeled). -/
def contract0 : AcceptedRecordContractDecl where
  contract := ⟨"Sample"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Accepted declaration for node `workers_alpha`. -/
def node0 : AcceptedNodeDecl where
  node := ⟨"workers_alpha"⟩
  nodeValid := by decide
  inputs := ∅
  outputs := [.single ⟨⟨"workers_alpha"⟩, ⟨"Sample"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `workers_beta`. -/
def node1 : AcceptedNodeDecl where
  node := ⟨"workers_beta"⟩
  nodeValid := by decide
  inputs := ∅
  outputs := [.single ⟨⟨"workers_beta"⟩, ⟨"Sample"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Module shell assembled from the artifact's node rows. -/
def shell : AdmittedModuleShell where
  contracts := [contract0]
  contractsUnique := by decide
  kinds := []
  kindsUnique := by decide
  nodes := [node0, node1]
  nodesUnique := by decide
  graphs := []
  graphsUnique := by decide
  graphsValid := fun _ hGraph => nomatch hGraph
  recordFieldContractsClosed := by
    intro contract hContract
    fin_cases hContract <;> exact fun _ hField => nomatch hField
  nodeContractsClosed := by
    intro node hNode
    fin_cases hNode <;>
      refine ⟨fun port hPort => ?_, fun port hPort => ?_⟩ <;>
        fin_cases hPort <;>
          exact ContractId.ClosedBy.declared (by decide)
  kindContractsClosed := fun _ hKind => nomatch hKind
  graphRefsClosed := fun _ hGraph => nomatch hGraph

/-- Core expression reconstructed from the artifact's primitive trace
(binding annotations skipped; the differential is frontier-level). -/
def expr : GraphExpr := .overlay (.node ⟨"workers_alpha"⟩) (.node ⟨"workers_beta"⟩)

/-- Output frontier the compiler exposed for this fixture. -/
def expectedOutputs : Finset (SourcePortInstance NodeId OutputPortSignature) :=
  { ⟨⟨"workers_alpha"⟩, ⟨⟨⟨"workers_alpha"⟩, ⟨"Sample"⟩⟩⟩⟩
  , ⟨⟨"workers_beta"⟩, ⟨⟨⟨"workers_beta"⟩, ⟨"Sample"⟩⟩⟩⟩
  }

/-- Input frontier the compiler exposed for this fixture. -/
def expectedInputs : Finset (SourcePortInstance NodeId InputPortSignature) := ∅

-- The kernel replays the compiler's composition onto the same boundary.
#guard
  match CertifiedGraph.elaborate shell expr with
  | .ok result =>
      decide (result.val.object.graph.exposedOutputs = expectedOutputs) &&
        decide (result.val.object.graph.exposedInputs = expectedInputs)
  | .error _ => false

end DifferentialMakeEach
end AdmissionArtifact
end Cortex.Wire
