import Cortex.Wire.ElaborationIRDecide
import Cortex.Wire.GraphElaborationExec
import Mathlib.Tactic.FinCases

/-!
## Overview

Differential oracle for the `RecordScatter` fixture: the
executable admission kernel replays the compiler's composition (reconstructed
from the emitted artifact's primitive trace, binding annotations skipped)
against a module shell assembled from the artifact's node rows, and must land
on the exposed boundary the compiler recorded.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures`; the Haskell test suite fails on drift.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace DifferentialRecordScatter

open Cortex.Wire.ElaborationIR

/-- Declared contract `Pair` (closure row; fields are not modeled). -/
def contract0 : AcceptedRecordContractDecl where
  contract := ⟨"Pair"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Declared contract `A` (closure row; fields are not modeled). -/
def contract1 : AcceptedRecordContractDecl where
  contract := ⟨"A"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Declared contract `B` (closure row; fields are not modeled). -/
def contract2 : AcceptedRecordContractDecl where
  contract := ⟨"B"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Declared contract `Done` (closure row; fields are not modeled). -/
def contract3 : AcceptedRecordContractDecl where
  contract := ⟨"Done"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Accepted declaration for node `source`. -/
def node0 : AcceptedNodeDecl where
  node := ⟨"source"⟩
  nodeValid := by decide
  inputs := ∅
  outputs := [.single ⟨⟨"pair"⟩, ⟨"Pair"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `__star:scatter:7dc42cd924f2`. -/
def node1 : AcceptedNodeDecl where
  node := ⟨"__star:scatter:7dc42cd924f2"⟩
  nodeValid := by decide
  inputs := {⟨⟨"pair"⟩, ⟨"Pair"⟩⟩}
  outputs := [.single ⟨⟨"a"⟩, ⟨"A"⟩⟩, .single ⟨⟨"b"⟩, ⟨"B"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `a`. -/
def node2 : AcceptedNodeDecl where
  node := ⟨"a"⟩
  nodeValid := by decide
  inputs := {⟨⟨"a"⟩, ⟨"A"⟩⟩}
  outputs := [.single ⟨⟨"done_a"⟩, ⟨"Done"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `b`. -/
def node3 : AcceptedNodeDecl where
  node := ⟨"b"⟩
  nodeValid := by decide
  inputs := {⟨⟨"b"⟩, ⟨"B"⟩⟩}
  outputs := [.single ⟨⟨"done_b"⟩, ⟨"Done"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Module shell assembled from the artifact's node rows. -/
def shell : AdmittedModuleShell where
  contracts := [contract0, contract1, contract2, contract3]
  contractsUnique := by decide
  kinds := []
  kindsUnique := by decide
  nodes := [node0, node1, node2, node3]
  nodesUnique := by decide
  graphs := []
  graphsUnique := by decide
  graphsValid := fun _ hGraph => nomatch hGraph
  recordFieldContractsClosed := by
    intro contract hContract
    fin_cases hContract <;> exact fun _ hField => nomatch hField
  nodeContractsClosed := by
    intro node hNode
    fin_cases hNode <;>
      refine ⟨fun port hPort => ?_, fun port hPort => ?_⟩ <;>
        fin_cases hPort <;>
          exact ContractId.ClosedBy.declared (by decide)
  kindContractsClosed := fun _ hKind => nomatch hKind
  graphRefsClosed := fun _ hGraph => nomatch hGraph

/-- Core expression reconstructed from the artifact's primitive trace
(binding annotations skipped; the differential is frontier-level). -/
def expr : GraphExpr :=
  .connect
      (.connect (.node ⟨"source"⟩) (.node ⟨"__star:scatter:7dc42cd924f2"⟩))
      (.overlay (.node ⟨"a"⟩) (.node ⟨"b"⟩))

/-- Output frontier the compiler exposed for this fixture. -/
def expectedOutputs : Finset (SourcePortInstance NodeId OutputPortSignature) :=
  {⟨⟨"a"⟩, ⟨⟨⟨"done_a"⟩, ⟨"Done"⟩⟩⟩⟩, ⟨⟨"b"⟩, ⟨⟨⟨"done_b"⟩, ⟨"Done"⟩⟩⟩⟩}

/-- Input frontier the compiler exposed for this fixture. -/
def expectedInputs : Finset (SourcePortInstance NodeId InputPortSignature) := ∅

-- The kernel replays the compiler's composition onto the same boundary.
#guard
  match CertifiedGraph.elaborate shell expr with
  | .ok result =>
      decide (result.val.object.graph.exposedOutputs = expectedOutputs) &&
        decide (result.val.object.graph.exposedInputs = expectedInputs)
  | .error _ => false

end DifferentialRecordScatter
end AdmissionArtifact
end Cortex.Wire
