import Cortex.Wire.ElaborationIRDecide
import Cortex.Wire.GraphElaborationExec
import Mathlib.Tactic.FinCases

/-!
## Overview

Differential oracle for the `SelectContract` fixture: the
executable admission kernel replays the compiler's composition (reconstructed
from the emitted artifact's primitive trace, binding annotations skipped)
against a module shell assembled from the artifact's node rows, and must land
on the exposed boundary the compiler recorded.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures`; the Haskell test suite fails on drift.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace DifferentialSelectContract

open Cortex.Wire.ElaborationIR

/-- Declared contract `DraftPlan` (closure row; fields are not modeled). -/
def contract0 : AcceptedRecordContractDecl where
  contract := ⟨"DraftPlan"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Declared contract `PlanIssue` (closure row; fields are not modeled). -/
def contract1 : AcceptedRecordContractDecl where
  contract := ⟨"PlanIssue"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Declared contract `ResearchPlan` (closure row; fields are not modeled). -/
def contract2 : AcceptedRecordContractDecl where
  contract := ⟨"ResearchPlan"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Declared contract `ReportArtifactRef` (closure row; fields are not modeled). -/
def contract3 : AcceptedRecordContractDecl where
  contract := ⟨"ReportArtifactRef"⟩
  contractValid := by decide
  fields := []
  fieldsValid := by decide
  fieldLabelsUnique := by decide

/-- Accepted declaration for node `draft_plan`. -/
def node0 : AcceptedNodeDecl where
  node := ⟨"draft_plan"⟩
  nodeValid := by decide
  inputs := ∅
  outputs := [.single ⟨⟨"draft"⟩, ⟨"DraftPlan"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `validate_plan`. -/
def node1 : AcceptedNodeDecl where
  node := ⟨"validate_plan"⟩
  nodeValid := by decide
  inputs := {⟨⟨"draft"⟩, ⟨"DraftPlan"⟩⟩}
  outputs := [.single ⟨⟨"valid"⟩, ⟨"ResearchPlan"⟩⟩, .single ⟨⟨"issue"⟩, ⟨"PlanIssue"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `__select:ResearchPlan_PlanIssue:daae5c794e93`. -/
def node2 : AcceptedNodeDecl where
  node := ⟨"__select:ResearchPlan_PlanIssue:daae5c794e93"⟩
  nodeValid := by decide
  inputs := {⟨⟨"valid"⟩, ⟨"ResearchPlan"⟩⟩, ⟨⟨"issue"⟩, ⟨"PlanIssue"⟩⟩}
  outputs := [.single ⟨⟨"valid"⟩, ⟨"ResearchPlan"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Accepted declaration for node `publish_report`. -/
def node3 : AcceptedNodeDecl where
  node := ⟨"publish_report"⟩
  nodeValid := by decide
  inputs := {⟨⟨"valid"⟩, ⟨"ResearchPlan"⟩⟩}
  outputs := [.single ⟨⟨"report"⟩, ⟨"ReportArtifactRef"⟩⟩]
  inputPortsValid := by decide
  outputShapesAdmissible := by decide
  outputPortsListLabelsUnique := by decide
  inputLabelsUnique := by decide
  body := .corePure
  bodyLocalValid := by decide

/-- Module shell assembled from the artifact's node rows. -/
def shell : AdmittedModuleShell where
  contracts := [contract0, contract1, contract2, contract3]
  contractsUnique := by decide
  kinds := []
  kindsUnique := by decide
  nodes := [node0, node1, node2, node3]
  nodesUnique := by decide
  graphs := []
  graphsUnique := by decide
  graphsValid := fun _ hGraph => nomatch hGraph
  recordFieldContractsClosed := by
    intro contract hContract
    fin_cases hContract <;> exact fun _ hField => nomatch hField
  nodeContractsClosed := by
    intro node hNode
    fin_cases hNode <;>
      refine ⟨fun port hPort => ?_, fun port hPort => ?_⟩ <;>
        fin_cases hPort <;>
          exact ContractId.ClosedBy.declared (by decide)
  kindContractsClosed := fun _ hKind => nomatch hKind
  graphRefsClosed := fun _ hGraph => nomatch hGraph

/-- Core expression reconstructed from the artifact's primitive trace
(binding annotations skipped; the differential is frontier-level). -/
def expr : GraphExpr :=
  .connect
      ( .connect
            (.connect (.node ⟨"draft_plan"⟩) (.node ⟨"validate_plan"⟩))
            (.node ⟨"__select:ResearchPlan_PlanIssue:daae5c794e93"⟩)
      )
      (.node ⟨"publish_report"⟩)

/-- Output frontier the compiler exposed for this fixture. -/
def expectedOutputs : Finset (SourcePortInstance NodeId OutputPortSignature) :=
  {⟨⟨"publish_report"⟩, ⟨⟨⟨"report"⟩, ⟨"ReportArtifactRef"⟩⟩⟩⟩}

/-- Input frontier the compiler exposed for this fixture. -/
def expectedInputs : Finset (SourcePortInstance NodeId InputPortSignature) := ∅

-- The kernel replays the compiler's composition onto the same boundary.
#guard
  match CertifiedGraph.elaborate shell expr with
  | .ok result =>
      decide (result.val.object.graph.exposedOutputs = expectedOutputs) &&
        decide (result.val.object.graph.exposedInputs = expectedInputs)
  | .error _ => false

end DifferentialSelectContract
end AdmissionArtifact
end Cortex.Wire
