-- Cortex-owned Pulse schema fixture for the test database.
-- Generated by scripts (extract-pulse-schema) from the applied pulse
-- migration sequence, then pg_dump -n pulse. Do not edit by hand;
-- regenerate when the Pulse schema changes. Cortex owns its substrate
-- schema (ADR 0003); this fixture has no downstream coupling.

--
-- PostgreSQL database dump
--

\restrict DOlga0R2I8dGBjDPPixbHVuE2Odt9zBedCgHJMt1barnnDbmVmzS3Nz4JmmmMgr

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pulse; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA pulse;


--
-- Name: run_status; Type: TYPE; Schema: pulse; Owner: -
--

CREATE TYPE pulse.run_status AS ENUM (
    'pending',
    'running',
    'waiting',
    'completed',
    'failed',
    'cancelled',
    'timeout',
    'skipped'
);


--
-- Name: stage_status; Type: TYPE; Schema: pulse; Owner: -
--

CREATE TYPE pulse.stage_status AS ENUM (
    'started',
    'completed',
    'failed',
    'skipped'
);


--
-- Name: trigger_source; Type: TYPE; Schema: pulse; Owner: -
--

CREATE TYPE pulse.trigger_source AS ENUM (
    'schedule',
    'manual',
    'retry'
);


--
-- Name: update_run_duration(); Type: FUNCTION; Schema: pulse; Owner: -
--

CREATE FUNCTION pulse.update_run_duration() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.completed_at IS NOT NULL AND OLD.completed_at IS NULL THEN
        NEW.duration := NEW.completed_at - NEW.started_at;
    END IF;
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: checkpoints; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.checkpoints (
    run_id uuid NOT NULL,
    task_type text NOT NULL,
    checkpoint_name text NOT NULL,
    state jsonb NOT NULL,
    summary jsonb,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: graph_rewrites; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.graph_rewrites (
    rewrite_id bigint NOT NULL,
    run_id uuid NOT NULL,
    source_node_id text NOT NULL,
    rewrite_spec jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    source_node_output jsonb,
    rewrite_cost jsonb,
    rewrite_delta jsonb,
    budget_before jsonb,
    budget_after jsonb,
    status text DEFAULT 'admitted'::text NOT NULL,
    rejection_reason text,
    exceeded_dimensions jsonb,
    admission_mode text DEFAULT 'gassed'::text NOT NULL,
    CONSTRAINT graph_rewrites_status_check CHECK ((status = ANY (ARRAY['admitted'::text, 'rejected'::text]))),
    CONSTRAINT graph_rewrites_admission_mode_check CHECK ((admission_mode = ANY (ARRAY['gassed'::text, 'witnessed'::text])))
);


--
-- Name: graph_rewrites_rewrite_id_seq; Type: SEQUENCE; Schema: pulse; Owner: -
--

ALTER TABLE pulse.graph_rewrites ALTER COLUMN rewrite_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME pulse.graph_rewrites_rewrite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: graph_state; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.graph_state (
    run_id uuid NOT NULL,
    node_statuses jsonb NOT NULL,
    node_outputs jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    runtime_version integer,
    applied_rewrite_id bigint,
    remaining_rewrite_budget jsonb,
    node_provenance jsonb,
    topology_hash text
);


--
-- Name: run_events; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.run_events (
    event_id bigint NOT NULL,
    run_id uuid NOT NULL,
    event_type text NOT NULL,
    severity text NOT NULL,
    message text NOT NULL,
    details jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: TABLE run_events; Type: COMMENT; Schema: pulse; Owner: -
--

COMMENT ON TABLE pulse.run_events IS 'Append-only lifecycle event history for Pulse runs. Never updated or deleted directly; CASCADE from runs.';


--
-- Name: COLUMN run_events.event_type; Type: COMMENT; Schema: pulse; Owner: -
--

COMMENT ON COLUMN pulse.run_events.event_type IS 'Short stable key: run.started, stage.completed, resume.replay_blocked, lease.lost, etc.';


--
-- Name: COLUMN run_events.severity; Type: COMMENT; Schema: pulse; Owner: -
--

COMMENT ON COLUMN pulse.run_events.severity IS 'Denormalized from observability level: info, warn, error.';


--
-- Name: COLUMN run_events.details; Type: COMMENT; Schema: pulse; Owner: -
--

COMMENT ON COLUMN pulse.run_events.details IS 'Structured context per event type: stage name, attempt number, error info, etc.';


--
-- Name: run_events_event_id_seq; Type: SEQUENCE; Schema: pulse; Owner: -
--

CREATE SEQUENCE pulse.run_events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: run_events_event_id_seq; Type: SEQUENCE OWNED BY; Schema: pulse; Owner: -
--

ALTER SEQUENCE pulse.run_events_event_id_seq OWNED BY pulse.run_events.event_id;


--
-- Name: runs; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.runs (
    run_id uuid DEFAULT gen_random_uuid() NOT NULL,
    task_id uuid NOT NULL,
    status pulse.run_status DEFAULT 'pending'::pulse.run_status NOT NULL,
    trigger_source pulse.trigger_source NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    duration interval,
    lease_owner text,
    lease_expires_at timestamp with time zone,
    cancel_requested_at timestamp with time zone,
    cancel_reason text,
    error_type text,
    error_message text,
    error_retryable boolean,
    skip_reason text,
    parent_run_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid
);


--
-- Name: signals; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.signals (
    signal_id bigint NOT NULL,
    run_id uuid NOT NULL,
    signal_name text NOT NULL,
    node_id text,
    status text DEFAULT 'pending'::text NOT NULL,
    payload jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    delivered_at timestamp with time zone,
    expires_at timestamp with time zone
);


--
-- Name: signals_signal_id_seq; Type: SEQUENCE; Schema: pulse; Owner: -
--

CREATE SEQUENCE pulse.signals_signal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: signals_signal_id_seq; Type: SEQUENCE OWNED BY; Schema: pulse; Owner: -
--

ALTER SEQUENCE pulse.signals_signal_id_seq OWNED BY pulse.signals.signal_id;


--
-- Name: stage_attempt_log; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.stage_attempt_log (
    attempt_id bigint NOT NULL,
    stage_log_id bigint NOT NULL,
    run_id uuid NOT NULL,
    attempt_number integer NOT NULL,
    status pulse.stage_status NOT NULL,
    summary jsonb,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT pulse_stage_attempt_log_attempt_number_positive CHECK ((attempt_number >= 1))
);


--
-- Name: stage_attempt_log_attempt_id_seq; Type: SEQUENCE; Schema: pulse; Owner: -
--

CREATE SEQUENCE pulse.stage_attempt_log_attempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: stage_attempt_log_attempt_id_seq; Type: SEQUENCE OWNED BY; Schema: pulse; Owner: -
--

ALTER SEQUENCE pulse.stage_attempt_log_attempt_id_seq OWNED BY pulse.stage_attempt_log.attempt_id;


--
-- Name: stage_log; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.stage_log (
    id bigint NOT NULL,
    run_id uuid NOT NULL,
    stage_name text NOT NULL,
    status pulse.stage_status NOT NULL,
    state_summary jsonb,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);


--
-- Name: stage_log_id_seq; Type: SEQUENCE; Schema: pulse; Owner: -
--

CREATE SEQUENCE pulse.stage_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: stage_log_id_seq; Type: SEQUENCE OWNED BY; Schema: pulse; Owner: -
--

ALTER SEQUENCE pulse.stage_log_id_seq OWNED BY pulse.stage_log.id;


--
-- Name: task_definitions; Type: TABLE; Schema: pulse; Owner: -
--

CREATE TABLE pulse.task_definitions (
    task_id uuid DEFAULT gen_random_uuid() NOT NULL,
    task_type text NOT NULL,
    task_name text NOT NULL,
    config jsonb NOT NULL,
    cron_expression text DEFAULT ''::text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    next_run_at timestamp with time zone,
    last_run_at timestamp with time zone,
    last_run_status pulse.run_status,
    timeout_seconds integer DEFAULT 3600 NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    min_interval_seconds integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    scheduler_claimed boolean DEFAULT false NOT NULL
);


--
-- Name: COLUMN task_definitions.next_run_at; Type: COMMENT; Schema: pulse; Owner: -
--

COMMENT ON COLUMN pulse.task_definitions.next_run_at IS 'Next scheduled execution time. NULL means hidden from scheduler: either completed one-off (enabled=false) or disabled recurring. Use with enabled + cron_expression + scheduler_claimed to determine full state.';


--
-- Name: COLUMN task_definitions.priority; Type: COMMENT; Schema: pulse; Owner: -
--

COMMENT ON COLUMN pulse.task_definitions.priority IS 'Scheduling priority. Higher values are claimed first. Default 0.';


--
-- Name: COLUMN task_definitions.min_interval_seconds; Type: COMMENT; Schema: pulse; Owner: -
--

COMMENT ON COLUMN pulse.task_definitions.min_interval_seconds IS 'Minimum seconds between consecutive runs of this task. NULL means no cooldown. Scheduler skips tasks within their cooldown window.';


--
-- Name: run_events event_id; Type: DEFAULT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.run_events ALTER COLUMN event_id SET DEFAULT nextval('pulse.run_events_event_id_seq'::regclass);


--
-- Name: signals signal_id; Type: DEFAULT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.signals ALTER COLUMN signal_id SET DEFAULT nextval('pulse.signals_signal_id_seq'::regclass);


--
-- Name: stage_attempt_log attempt_id; Type: DEFAULT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.stage_attempt_log ALTER COLUMN attempt_id SET DEFAULT nextval('pulse.stage_attempt_log_attempt_id_seq'::regclass);


--
-- Name: stage_log id; Type: DEFAULT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.stage_log ALTER COLUMN id SET DEFAULT nextval('pulse.stage_log_id_seq'::regclass);


--
-- Name: checkpoints checkpoints_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.checkpoints
    ADD CONSTRAINT checkpoints_pkey PRIMARY KEY (run_id);


--
-- Name: graph_rewrites graph_rewrites_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.graph_rewrites
    ADD CONSTRAINT graph_rewrites_pkey PRIMARY KEY (rewrite_id);


--
-- Name: graph_state graph_state_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.graph_state
    ADD CONSTRAINT graph_state_pkey PRIMARY KEY (run_id);


--
-- Name: stage_attempt_log pulse_stage_attempt_log_unique_attempt; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.stage_attempt_log
    ADD CONSTRAINT pulse_stage_attempt_log_unique_attempt UNIQUE (stage_log_id, attempt_number);


--
-- Name: run_events run_events_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.run_events
    ADD CONSTRAINT run_events_pkey PRIMARY KEY (event_id);


--
-- Name: runs runs_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.runs
    ADD CONSTRAINT runs_pkey PRIMARY KEY (run_id);


--
-- Name: signals signals_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.signals
    ADD CONSTRAINT signals_pkey PRIMARY KEY (signal_id);


--
-- Name: stage_attempt_log stage_attempt_log_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.stage_attempt_log
    ADD CONSTRAINT stage_attempt_log_pkey PRIMARY KEY (attempt_id);


--
-- Name: stage_log stage_log_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.stage_log
    ADD CONSTRAINT stage_log_pkey PRIMARY KEY (id);


--
-- Name: task_definitions task_definitions_pkey; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.task_definitions
    ADD CONSTRAINT task_definitions_pkey PRIMARY KEY (task_id);


--
-- Name: task_definitions task_definitions_task_name_key; Type: CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.task_definitions
    ADD CONSTRAINT task_definitions_task_name_key UNIQUE (task_name);


--
-- Name: idx_pulse_graph_rewrites_run_id; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_graph_rewrites_run_id ON pulse.graph_rewrites USING btree (run_id);


--
-- Name: idx_pulse_run_events_run; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_run_events_run ON pulse.run_events USING btree (run_id, created_at, event_id);


--
-- Name: idx_pulse_runs_lease_owner; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_runs_lease_owner ON pulse.runs USING btree (lease_owner) WHERE (status = 'running'::pulse.run_status);


--
-- Name: idx_pulse_runs_lease_recovery; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_runs_lease_recovery ON pulse.runs USING btree (lease_expires_at) WHERE (status = 'running'::pulse.run_status);


--
-- Name: idx_pulse_runs_open_task; Type: INDEX; Schema: pulse; Owner: -
--

CREATE UNIQUE INDEX idx_pulse_runs_open_task ON pulse.runs USING btree (task_id) WHERE (status = ANY (ARRAY['pending'::pulse.run_status, 'running'::pulse.run_status, 'waiting'::pulse.run_status]));


--
-- Name: idx_pulse_runs_status; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_runs_status ON pulse.runs USING btree (status) WHERE (status = 'running'::pulse.run_status);


--
-- Name: idx_pulse_runs_task; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_runs_task ON pulse.runs USING btree (task_id, created_at DESC);


--
-- Name: idx_pulse_runs_user_id_created; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_runs_user_id_created ON pulse.runs USING btree (user_id, created_at DESC) WHERE (user_id IS NOT NULL);


--
-- Name: idx_pulse_signals_pending; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_signals_pending ON pulse.signals USING btree (run_id) WHERE (status = 'pending'::text);


--
-- Name: idx_pulse_signals_pending_unique; Type: INDEX; Schema: pulse; Owner: -
--

CREATE UNIQUE INDEX idx_pulse_signals_pending_unique ON pulse.signals USING btree (run_id, signal_name) WHERE (status = 'pending'::text);


--
-- Name: idx_pulse_signals_pending_name; Type: INDEX; Schema: pulse; Owner: -
-- Run-terminal delivery updates pending signals by signal_name (across runs);
-- without this partial index every terminal status write scans all pending
-- signals. Keep in sync with the downstream migration.
--

CREATE INDEX idx_pulse_signals_pending_name ON pulse.signals USING btree (signal_name) WHERE (status = 'pending'::text);


--
-- Name: idx_pulse_stage_attempt_log_run; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_stage_attempt_log_run ON pulse.stage_attempt_log USING btree (run_id, started_at, attempt_id);


--
-- Name: idx_pulse_stage_log_run; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_stage_log_run ON pulse.stage_log USING btree (run_id, started_at);


--
-- Name: idx_pulse_tasks_enabled; Type: INDEX; Schema: pulse; Owner: -
--

CREATE INDEX idx_pulse_tasks_enabled ON pulse.task_definitions USING btree (enabled, next_run_at) WHERE ((enabled = true) AND (scheduler_claimed = false));


--
-- Name: runs trigger_pulse_run_duration; Type: TRIGGER; Schema: pulse; Owner: -
--

CREATE TRIGGER trigger_pulse_run_duration BEFORE UPDATE ON pulse.runs FOR EACH ROW EXECUTE FUNCTION pulse.update_run_duration();


--
-- Name: checkpoints checkpoints_run_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.checkpoints
    ADD CONSTRAINT checkpoints_run_id_fkey FOREIGN KEY (run_id) REFERENCES pulse.runs(run_id);


--
-- Name: graph_rewrites graph_rewrites_run_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.graph_rewrites
    ADD CONSTRAINT graph_rewrites_run_id_fkey FOREIGN KEY (run_id) REFERENCES pulse.runs(run_id) ON DELETE CASCADE;


--
-- Name: graph_state graph_state_run_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.graph_state
    ADD CONSTRAINT graph_state_run_id_fkey FOREIGN KEY (run_id) REFERENCES pulse.runs(run_id) ON DELETE CASCADE;


--
-- Name: run_events run_events_run_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.run_events
    ADD CONSTRAINT run_events_run_id_fkey FOREIGN KEY (run_id) REFERENCES pulse.runs(run_id) ON DELETE CASCADE;


--
-- Name: runs runs_parent_run_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.runs
    ADD CONSTRAINT runs_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES pulse.runs(run_id);


--
-- Name: runs runs_task_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.runs
    ADD CONSTRAINT runs_task_id_fkey FOREIGN KEY (task_id) REFERENCES pulse.task_definitions(task_id);


--
-- Name: signals signals_run_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.signals
    ADD CONSTRAINT signals_run_id_fkey FOREIGN KEY (run_id) REFERENCES pulse.runs(run_id) ON DELETE CASCADE;


--
-- Name: stage_attempt_log stage_attempt_log_run_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.stage_attempt_log
    ADD CONSTRAINT stage_attempt_log_run_id_fkey FOREIGN KEY (run_id) REFERENCES pulse.runs(run_id) ON DELETE CASCADE;


--
-- Name: stage_attempt_log stage_attempt_log_stage_log_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.stage_attempt_log
    ADD CONSTRAINT stage_attempt_log_stage_log_id_fkey FOREIGN KEY (stage_log_id) REFERENCES pulse.stage_log(id) ON DELETE CASCADE;


--
-- Name: stage_log stage_log_run_id_fkey; Type: FK CONSTRAINT; Schema: pulse; Owner: -
--

ALTER TABLE ONLY pulse.stage_log
    ADD CONSTRAINT stage_log_run_id_fkey FOREIGN KEY (run_id) REFERENCES pulse.runs(run_id);


--
-- PostgreSQL database dump complete
--

\unrestrict DOlga0R2I8dGBjDPPixbHVuE2Odt9zBedCgHJMt1barnnDbmVmzS3Nz4JmmmMgr



--
-- Name: external_call_attempts; Type: TABLE; Schema: pulse; Owner: -
-- ADR 0059 §3: durable home for a submit/park/resume external call's idempotency
-- key, frozen fused plan, provider job handle, and completion signal name.
--

CREATE TABLE pulse.external_call_attempts (
    attempt_id bigserial PRIMARY KEY,
    run_id uuid NOT NULL,
    node_id text NOT NULL,
    runtime_binding_id text NOT NULL,
    frontier_id text NOT NULL,
    idempotency_key text NOT NULL,
    frozen_plan jsonb NOT NULL,
    job_handle jsonb,
    signal_name text,
    status text DEFAULT 'reserved'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    submitted_at timestamp with time zone,
    settled_at timestamp with time zone
);

CREATE UNIQUE INDEX idx_pulse_external_call_attempts_key
    ON pulse.external_call_attempts USING btree (run_id, node_id, runtime_binding_id, frontier_id);
