{- |
Module      : Cortex.Wire.LeanFixture
Description : Render emitted Wire admission artifacts as Lean fixture modules.
Copyright   : (c) 2026 Digimuoto Oy
License     : Apache-2.0
Maintainer  : julius.koskela@digimuoto.com
Stability   : experimental

Renders a compiled circuit's 'WireAdmissionArtifact' as Lean source in the
shape of @theory/Cortex/Wire/AdmissionArtifact/EmittedFixture.lean@: a value
definition, a @#guard@ running the Lean-owned executable validator, and a
soundness theorem discharged by @native_decide@. The generated modules are
checked into @theory/@ so @just lean-check@ validates real compiler output;
the Haskell test suite re-renders each fixture and fails on drift.
-}
module Cortex.Wire.LeanFixture
  ( EmittedFixture (..)
  , emittedFixtures
  , emittedFixtureModuleName
  , emittedFixtureNamespace
  , renderEmittedFixtureModule
  , renderEmittedUmbrellaModule
  , renderFixtureModuleText
  , compiledWireAdmissionArtifact
  , differentialFixtures
  , renderDifferentialModuleText
  , renderDifferentialUmbrellaModule
  ) where

import Data.Aeson qualified as Aeson
import Data.Aeson.Key qualified as AesonKey
import Data.Aeson.KeyMap qualified as AesonKeyMap
import Data.Map.Strict qualified as Map
import Data.Maybe (isJust)
import Data.Text (Text)
import Data.Text qualified as T
import Numeric.Natural (Natural)

import Cortex.Wire.AST (Connection (..), EndpointRef (..))
import Cortex.Wire.AST qualified as WireCore
import Cortex.Wire.AdmissionArtifact
import Cortex.Wire.Circuit.Compiled (CompiledCircuit (..))
import Cortex.Wire.Circuit.IR (CircuitNodeRef (..))
import Cortex.Wire.Compile (compileWireFragmentTextWithEnv)
import Cortex.Wire.Contracts
  ( WireCompileEnv (..)
  , WireContractSpec (..)
  , emptyWireCompileEnv
  , wireContractRegistryFromList
  )
import Cortex.Wire.Syntax (ContractId (..))
import Cortex.Wire.Value (WirePayloadKind (..))

-- | A Wire source fixture whose emitted artifact becomes a Lean module.
data EmittedFixture = EmittedFixture
  { emittedFixtureSlug :: !Text
  -- ^ Lean module suffix, e.g. @Chain@ for @...Emitted.Chain@.
  , emittedFixtureDescription :: !Text
  , emittedFixtureSource :: !Text
  , emittedFixtureEnv :: !WireCompileEnv
  {- ^ Compile environment; record-form phantom fixtures need a contract
  registry that declares their nominal record shape.
  -}
  }

emittedFixtureModuleName :: EmittedFixture -> Text
emittedFixtureModuleName fixture =
  "Cortex.Wire.AdmissionArtifact.Emitted." <> fixture.emittedFixtureSlug

emittedFixtureNamespace :: EmittedFixture -> Text
emittedFixtureNamespace fixture =
  "Emitted" <> fixture.emittedFixtureSlug

-- | Extract the admission artifact a compilation attached to its circuit.
compiledWireAdmissionArtifact :: CompiledCircuit -> Maybe WireAdmissionArtifact
compiledWireAdmissionArtifact compiled =
  case compiled.compiledCircuitMetadata of
    Aeson.Object obj -> do
      admission <- AesonKeyMap.lookup (AesonKey.fromText wireAdmissionMetadataKey) obj
      case Aeson.fromJSON admission of
        Aeson.Success artifact -> Just artifact
        Aeson.Error _message -> Nothing
    _ -> Nothing

-- | Compile a fixture source and render its artifact as a Lean module.
renderEmittedFixtureModule :: EmittedFixture -> Either WireCore.WireError Text
renderEmittedFixtureModule fixture = do
  compiled <- compileWireFragmentTextWithEnv fixture.emittedFixtureEnv fixture.emittedFixtureSource
  artifact <- case compiledWireAdmissionArtifact compiled of
    Just artifact -> Right artifact
    Nothing ->
      Left
        ( WireCore.WireParseError
            ("compiled fixture carries no admission artifact: " <> fixture.emittedFixtureSlug)
        )
  Right (renderFixtureModuleText fixture artifact)

-- | Umbrella module importing every generated fixture module.
renderEmittedUmbrellaModule :: [EmittedFixture] -> Text
renderEmittedUmbrellaModule fixtures =
  T.unlines
    ( fmap (\fixture -> "import " <> emittedFixtureModuleName fixture) fixtures
        <> [ ""
           , "/-!"
           , "## Overview"
           , ""
           , "Umbrella for the generated emitted-artifact fixtures. Each import is a"
           , "Lean module generated from a compiled Wire fixture by"
           , "`Cortex.Wire.LeanFixture`; regenerate with `just wire-lean-fixtures`."
           , "The Haskell test suite fails when any generated module drifts from the"
           , "current compiler output."
           , "-/"
           ]
    )

renderFixtureModuleText :: EmittedFixture -> WireAdmissionArtifact -> Text
renderFixtureModuleText fixture artifact =
  T.unlines
    ( [ "import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck"
      , ""
      , "/-!"
      , "## Overview"
      , ""
      , "Wire admission artifact emitted by the Haskell compiler for the"
      , T.concat ["`", fixture.emittedFixtureSlug, "` fixture: ", fixture.emittedFixtureDescription, "."]
      , ""
      , "GENERATED FILE - do not edit by hand. Regenerated by"
      , "`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test"
      , "suite fails when this file drifts from the current compiler output."
      , "`validatorReadyCheck_soundness` lifts the build-time boolean check below to"
      , "`WireAdmissionArtifact.Sound` for this artifact."
      , "-/"
      , ""
      , "namespace Cortex.Wire"
      , "namespace AdmissionArtifact"
      , "namespace " <> emittedFixtureNamespace fixture
      , ""
      ]
        <> artifactDocComment fixture.emittedFixtureDescription
        <> [ "def artifact : WireAdmissionArtifact where"
           ]
        <> concatMap (renderArtifactField 2) (artifactFields artifact)
        <> [ ""
           , "-- The Lean-owned executable validator accepts the emitted artifact."
           , "#guard artifact.validatorReadyCheck"
           , ""
           , "/-- The accepted artifact satisfies the proof-facing soundness contract. -/"
           , "theorem artifact_sound : artifact.Sound :="
           , "  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)"
           , ""
           , "end " <> emittedFixtureNamespace fixture
           , "end AdmissionArtifact"
           , "end Cortex.Wire"
           ]
    )

-- | Docstring for the artifact definition, wrapped under the lint width.
artifactDocComment :: Text -> [Text]
artifactDocComment description
  | T.length oneLine <= maxLineWidth = [oneLine]
  | otherwise =
      [ "/-- Emitted admission artifact for the"
      , description <> " fixture. -/"
      ]
  where
    oneLine = "/-- Emitted admission artifact for the " <> description <> " fixture. -/"

renderArtifactField :: Int -> (Text, LeanValue) -> [Text]
renderArtifactField indent (name, value) =
  case renderLeanValue (indent + 2) value of
    [single]
      | indent + T.length name + 4 + T.length single <= maxLineWidth ->
          [spaces indent <> name <> " := " <> single]
    valueLines ->
      (spaces indent <> name <> " :=")
        : indentFirst (indent + 2) valueLines

artifactFields :: WireAdmissionArtifact -> [(Text, LeanValue)]
artifactFields artifact =
  [ ("schemaVersion", naturalValue artifact.wireAdmissionSchemaVersion)
  , ("closureMode", closureModeValue artifact.wireAdmissionClosureMode)
  , ("nodes", LeanList (fmap nodeRefValue artifact.wireAdmissionNodes))
  , ("bindingRefs", LeanList (fmap anonText artifact.wireAdmissionBindingRefs))
  , ("entries", LeanList (fmap boundaryPortValue artifact.wireAdmissionEntries))
  , ("exits", LeanList (fmap boundaryPortValue artifact.wireAdmissionExits))
  , ("connections", LeanList (fmap rawConnectionValue artifact.wireAdmissionConnections))
  , ("primitiveSteps", LeanList (fmap primitiveStepValue artifact.wireAdmissionPrimitiveSteps))
  , ("generatedForms", LeanList (fmap generatedFormValue artifact.wireAdmissionGeneratedForms))
  , ("phantomAdapters", LeanList (fmap phantomAdapterValue artifact.wireAdmissionPhantomAdapters))
  , ("selects", LeanList (fmap selectValue artifact.wireAdmissionSelects))
  , ("endpointUses", endpointUseWitnessValue artifact.wireAdmissionEndpointUses)
  ]

-- Value translation ---------------------------------------------------------

nodeRefValue :: CircuitNodeRef -> LeanValue
nodeRefValue ref = anonText ref.unCircuitNodeRef

anonText :: Text -> LeanValue
anonText text = LeanAtom ("\10216" <> leanStringLit text <> "\10217")

naturalValue :: Natural -> LeanValue
naturalValue = LeanAtom . T.pack . show

closureModeValue :: WireAdmissionClosureMode -> LeanValue
closureModeValue = \case
  AdmissionClosedExecutable -> LeanAtom ".closedExecutable"
  AdmissionOpenFragment -> LeanAtom ".openFragment"

boundaryPortValue :: AdmissionBoundaryPort -> LeanValue
boundaryPortValue boundary =
  LeanRecord
    [ ("node", nodeRefValue boundary.admissionBoundaryNode)
    , ("port", anonText boundary.admissionBoundaryPort)
    , ("contract", anonText boundary.admissionBoundaryContract)
    , ("label", portLabelValue boundary.admissionBoundaryLabel)
    , ("exclusiveGroup", exclusiveGroupValue boundary.admissionBoundaryExclusiveGroup)
    ]

portLabelValue :: AdmissionPortLabel -> LeanValue
portLabelValue = \case
  AdmissionNoLabel -> LeanAtom ".noLabel"
  AdmissionLabel label -> LeanApp ".label" [anonText label]

exclusiveGroupValue :: Maybe (CircuitNodeRef, Natural) -> LeanValue
exclusiveGroupValue = \case
  Nothing -> LeanAtom "none"
  Just (owner, groupIndex) ->
    LeanApp "some" [LeanTuple [nodeRefValue owner, naturalValue groupIndex]]

rawConnectionValue :: Connection -> LeanValue
rawConnectionValue connection =
  LeanRecord
    [ ("fromEndpoint", endpointValue connection.connectionFrom)
    , ("toEndpoint", endpointValue connection.connectionTo)
    ]

endpointValue :: EndpointRef -> LeanValue
endpointValue endpoint =
  LeanRecord
    [ ("node", nodeRefValue endpoint.endpointNodeRef)
    ,
      ( "port"
      , case endpoint.endpointPortName of
          Nothing -> LeanAtom "none"
          Just port -> LeanApp "some" [anonText port]
      )
    ]

matchedPairValue :: AdmissionConnection -> LeanValue
matchedPairValue connection =
  LeanRecord
    [ ("fromPort", boundaryPortValue connection.admissionConnectionFrom)
    , ("toPort", boundaryPortValue connection.admissionConnectionTo)
    ]

primitiveStepValue :: PrimitiveGraphStep -> LeanValue
primitiveStepValue = \case
  PrimitiveEmpty ->
    LeanAtom ".empty"
  PrimitiveNode node entries exits ->
    LeanApp
      ".node"
      [ nodeRefValue node
      , LeanList (fmap boundaryPortValue entries)
      , LeanList (fmap boundaryPortValue exits)
      ]
  PrimitiveBindingRef binding ->
    LeanApp ".bindingRef" [anonText binding]
  PrimitiveOverlay leftNodes rightNodes leftBindings rightBindings ->
    LeanApp
      ".overlay"
      [ LeanList (fmap nodeRefValue leftNodes)
      , LeanList (fmap nodeRefValue rightNodes)
      , LeanList (fmap anonText leftBindings)
      , LeanList (fmap anonText rightBindings)
      ]
  PrimitiveConnect leftExits rightEntries matchedPairs unmatchedLeftExits unmatchedRightEntries ->
    LeanApp
      ".connect"
      [ LeanList (fmap boundaryPortValue leftExits)
      , LeanList (fmap boundaryPortValue rightEntries)
      , LeanList (fmap matchedPairValue matchedPairs)
      , LeanList (fmap boundaryPortValue unmatchedLeftExits)
      , LeanList (fmap boundaryPortValue unmatchedRightEntries)
      ]

generatedFormValue :: GeneratedFormArtifact -> LeanValue
generatedFormValue form =
  LeanRecord
    [
      ( "kind"
      , case form.generatedFormKind of
          GeneratedMake -> LeanAtom ".make"
          GeneratedMakeEach -> LeanAtom ".makeEach"
      )
    , ("kindName", anonText form.generatedFormKindName)
    , ("binding", anonText form.generatedFormBinding)
    , ("sourceChildren", LeanList (fmap generatedChildSourceValue form.generatedFormSourceChildren))
    , ("usedChildren", LeanList (fmap generatedChildValue form.generatedFormUsedChildren))
    ]

generatedChildSourceValue :: GeneratedChildSourceArtifact -> LeanValue
generatedChildSourceValue child =
  LeanRecord
    [ ("node", nodeRefValue child.generatedSourceChildNode)
    , ("label", anonText child.generatedSourceChildLabel)
    ,
      ( "value"
      , case child.generatedSourceChildValue of
          Nothing -> LeanAtom "none"
          Just value -> LeanApp "some" [staticValueValue value]
      )
    ]

staticValueValue :: AdmissionStaticValue -> LeanValue
staticValueValue = \case
  AdmissionStaticString text -> LeanApp ".string" [LeanAtom (leanStringLit text)]
  AdmissionStaticBool boolValue ->
    LeanApp ".bool" [LeanAtom (if boolValue then "true" else "false")]
  AdmissionStaticNat natValue -> LeanApp ".nat" [naturalValue natValue]
  AdmissionStaticList values -> LeanApp ".list" [LeanList (fmap staticValueValue values)]
  AdmissionStaticRecord fields ->
    LeanApp
      ".record"
      [ LeanList
          ( fmap
              ( \field ->
                  LeanTuple
                    [ anonText field.admissionStaticFieldLabel
                    , staticValueValue field.admissionStaticFieldValue
                    ]
              )
              fields
          )
      ]

generatedChildValue :: GeneratedChildArtifact -> LeanValue
generatedChildValue child =
  LeanRecord
    [ ("node", nodeRefValue child.generatedChildNode)
    , ("label", anonText child.generatedChildLabel)
    , ("outputs", LeanList (fmap boundaryPortValue child.generatedChildOutputs))
    , ("inputs", LeanList (fmap boundaryPortValue child.generatedChildInputs))
    ]

phantomAdapterValue :: PhantomAdapterArtifact -> LeanValue
phantomAdapterValue adapter =
  LeanRecord
    [
      ( "direction"
      , case adapter.phantomAdapterDirection of
          PhantomGather -> LeanAtom ".gather"
          PhantomScatter -> LeanAtom ".scatter"
      )
    , ("node", nodeRefValue adapter.phantomAdapterNode)
    , ("productShape", productShapeValue adapter.phantomAdapterProductShape)
    , ("singular", boundaryPortValue adapter.phantomAdapterSingular)
    , ("multi", LeanList (fmap boundaryPortValue adapter.phantomAdapterMulti))
    , ("leftBulk", LeanList (fmap matchedPairValue adapter.phantomAdapterLeftBulk))
    , ("rightBulk", LeanList (fmap matchedPairValue adapter.phantomAdapterRightBulk))
    ]

productShapeValue :: ProductShapeArtifact -> LeanValue
productShapeValue = \case
  ProductRecord contract fields ->
    LeanApp
      ".record"
      [ anonText contract
      , LeanList
          (fmap (\(label, fieldContract) -> LeanTuple [anonText label, anonText fieldContract]) fields)
      ]
  ProductIndexed elementContract count ->
    LeanApp ".indexed" [anonText elementContract, naturalValue count]

selectValue :: SelectAdmissionArtifact -> LeanValue
selectValue select =
  LeanRecord
    [ ("owner", nodeRefValue select.selectAdmissionOwner)
    , ("variants", LeanList (fmap selectVariantValue select.selectAdmissionVariants))
    , ("arms", LeanList (fmap selectArmValue select.selectAdmissionArms))
    , ("conditionNode", nodeRefValue select.selectAdmissionConditionNode)
    ]

selectVariantValue :: SelectVariantArtifact -> LeanValue
selectVariantValue variant =
  LeanRecord
    [ ("key", anonText variant.selectVariantKey)
    , ("port", boundaryPortValue variant.selectVariantPort)
    ]

selectArmValue :: SelectArmAdmissionArtifact -> LeanValue
selectArmValue arm =
  LeanRecord
    [ ("sourceIndex", naturalValue arm.selectArmSourceIndex)
    , ("sourceKey", anonText arm.selectArmSourceKey)
    , ("canonicalKey", anonText arm.selectArmCanonicalKey)
    ,
      ( "mode"
      , case arm.selectArmResolutionMode of
          SelectResolvedByLabel -> LeanAtom ".resolvedByLabel"
          SelectResolvedByContract -> LeanAtom ".resolvedByContract"
      )
    , ("bodyNodes", LeanList (fmap nodeRefValue arm.selectArmBodyNodes))
    , ("bodyEntries", LeanList (fmap boundaryPortValue arm.selectArmBodyEntries))
    , ("bodyExits", LeanList (fmap boundaryPortValue arm.selectArmBodyExits))
    ]

endpointUseWitnessValue :: AdmissionEndpointUseWitness -> LeanValue
endpointUseWitnessValue witness =
  LeanRecord
    [ ("inputUses", LeanList (fmap inputUseWitnessValue witness.admissionEndpointInputUses))
    , ("outputUses", LeanList (fmap outputUseWitnessValue witness.admissionEndpointOutputUses))
    ]

inputUseWitnessValue :: AdmissionInputUseWitness -> LeanValue
inputUseWitnessValue witness =
  LeanRecord
    [ ("port", boundaryPortValue witness.admissionInputUsePort)
    , ("useKind", inputUseKindValue witness.admissionInputUseKind)
    ]

inputUseKindValue :: AdmissionInputUseKind -> LeanValue
inputUseKindValue = \case
  AdmissionProducedByEdge fromPort ->
    LeanApp ".producedByEdge" [boundaryPortValue fromPort]
  AdmissionHostInput ->
    LeanAtom ".hostInput"
  AdmissionImportedObligation ->
    LeanAtom ".importedObligation"

outputUseWitnessValue :: AdmissionOutputUseWitness -> LeanValue
outputUseWitnessValue witness =
  LeanRecord
    [ ("port", boundaryPortValue witness.admissionOutputUsePort)
    , ("useKind", outputUseKindValue witness.admissionOutputUseKind)
    ]

outputUseKindValue :: AdmissionOutputUseKind -> LeanValue
outputUseKindValue = \case
  AdmissionConsumedByEdge toPort ->
    LeanApp ".consumedByEdge" [boundaryPortValue toPort]
  AdmissionTerminalDischarge kind ->
    LeanApp ".terminalDischarge" [terminalDischargeKindValue kind]

terminalDischargeKindValue :: AdmissionTerminalDischargeKind -> LeanValue
terminalDischargeKindValue = \case
  AdmissionExportedBoundary -> LeanAtom ".exportedBoundary"
  AdmissionHostReturn -> LeanAtom ".hostReturn"
  AdmissionProofBoundarySink -> LeanAtom ".proofBoundarySink"

-- Lean value layout ----------------------------------------------------------

-- | Lean term skeleton: enough structure for artifact literals.
data LeanValue
  = LeanAtom !Text
  | LeanApp !Text ![LeanValue]
  | LeanList ![LeanValue]
  | LeanSet ![LeanValue]
  | LeanTuple ![LeanValue]
  | LeanRecord ![(Text, LeanValue)]

maxLineWidth :: Int
maxLineWidth = 96

spaces :: Int -> Text
spaces n = T.replicate n " "

leanString :: Text -> Text
leanString = T.concatMap escape
  where
    escape = \case
      '"' -> "\\\""
      '\\' -> "\\\\"
      '\n' -> "\\n"
      other -> T.singleton other

leanStringLit :: Text -> Text
leanStringLit text = "\"" <> leanString text <> "\""

inlineLeanValue :: LeanValue -> Text
inlineLeanValue = \case
  LeanAtom text -> text
  LeanApp constructor args ->
    T.unwords (constructor : fmap inlineArgument args)
  LeanList [] -> "[]"
  LeanList values -> "[" <> T.intercalate ", " (fmap inlineLeanValue values) <> "]"
  LeanSet [] -> "\8709"
  LeanSet values -> "{" <> T.intercalate ", " (fmap inlineLeanValue values) <> "}"
  LeanTuple values -> "(" <> T.intercalate ", " (fmap inlineLeanValue values) <> ")"
  LeanRecord fields ->
    "{ "
      <> T.intercalate ", " (fmap (\(name, value) -> name <> " := " <> inlineLeanValue value) fields)
      <> " }"

-- Constructor arguments that are themselves applications need parentheses.
inlineArgument :: LeanValue -> Text
inlineArgument value =
  case value of
    LeanApp _ (_ : _) -> "(" <> inlineLeanValue value <> ")"
    _ -> inlineLeanValue value

{- | Render a value at a column. The first line carries no indentation (the
caller splices it after its own prefix); continuation lines carry absolute
indentation relative to the given column.
-}
renderLeanValue :: Int -> LeanValue -> [Text]
renderLeanValue indent value
  | indent + T.length inline <= maxLineWidth = [inline]
  | otherwise = renderMultiline indent value
  where
    inline = inlineLeanValue value

renderMultiline :: Int -> LeanValue -> [Text]
renderMultiline indent = \case
  LeanAtom text ->
    [text]
  LeanApp constructor args ->
    constructor
      : concatMap (indentFirst (indent + 4) . renderApplicationArgument (indent + 4)) args
  LeanList [] ->
    ["[]"]
  LeanList values ->
    blockLines indent "[ " ", " "]" (fmap (renderLeanValue (indent + 2)) values)
  LeanSet [] ->
    ["\8709"]
  LeanSet values ->
    blockLines indent "{ " ", " "}" (fmap (renderLeanValue (indent + 2)) values)
  LeanTuple values ->
    blockLines indent "( " ", " ")" (fmap (renderLeanValue (indent + 2)) values)
  LeanRecord fields ->
    blockLines indent "{ " ", " "}" (fmap (renderRecordField indent) fields)

{- | Nested constructor applications need parentheses when laid out as
arguments; self-delimited shapes (lists, sets, records, atoms) do not.
-}
renderApplicationArgument :: Int -> LeanValue -> [Text]
renderApplicationArgument indent value =
  case value of
    LeanApp _ (_ : _) ->
      case renderLeanValue (indent + 2) value of
        [single]
          | indent + T.length single + 2 <= maxLineWidth ->
              ["(" <> single <> ")"]
        valueLines ->
          case valueLines of
            [] -> ["()"]
            firstLine : restLines ->
              ("( " <> firstLine) : restLines <> [spaces indent <> ")"]
    _selfDelimited -> renderLeanValue indent value

renderRecordField :: Int -> (Text, LeanValue) -> [Text]
renderRecordField indent (name, value) =
  case renderLeanValue (indent + 2) value of
    [single]
      | indent + 2 + T.length name + 4 + T.length single <= maxLineWidth ->
          [name <> " := " <> single]
    _multi ->
      (name <> " :=")
        : indentFirst (indent + 4) (renderLeanValue (indent + 4) value)

{- | Assemble bracketed multi-element layout: the opener fuses with the first
element, separators with each subsequent element, closer on its own line.
-}
blockLines :: Int -> Text -> Text -> Text -> [[Text]] -> [Text]
blockLines indent opener separator closer elements =
  case elements of
    [] ->
      [opener <> closer]
    firstElement : restElements ->
      attach opener firstElement
        <> concatMap (fmap (spaces indent <>) . attach' separator) restElements
        <> [spaces indent <> closer]
  where
    attach prefix element =
      case element of
        [] -> [prefix]
        firstLine : restLines -> (prefix <> firstLine) : restLines
    -- Continuation lines after the first already carry absolute indentation.
    attach' prefix element =
      case element of
        [] -> [prefix]
        firstLine : restLines ->
          (prefix <> firstLine) : fmap (T.drop indent) restLines

indentFirst :: Int -> [Text] -> [Text]
indentFirst indent = \case
  [] -> []
  firstLine : restLines -> (spaces indent <> firstLine) : restLines

-- Fixture corpus -------------------------------------------------------------

{- | Representative Wire programs covering every artifact component: primitive
chain, generated forms, phantom adapters in both directions and shapes, and
both select resolution modes. Sources mirror the CompileSpec fixtures of the
same names.
-}
emittedFixtures :: [EmittedFixture]
emittedFixtures =
  [ EmittedFixture
      { emittedFixtureSlug = "Chain"
      , emittedFixtureDescription = "labeled primitive chain (planner => analyst)"
      , emittedFixtureSource =
          T.unlines
            [ "node planner"
            , "  -> plan: PlannerOutput = @review.planner ({}) ;"
            , "node analyst"
            , "  <- plan: PlannerOutput ;"
            , "  -> analysis: AnalysisFragment = @review.analyst (plan) ;"
            , "planner => analyst"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "Make"
      , emittedFixtureDescription = "bounded make expansion (make(3, sample))"
      , emittedFixtureSource =
          T.unlines
            [ "kind sample(label: PortLabel) ="
            , "  -> label: Sample = @review.sample ({}) ;"
            , "let workers = make(3, sample);"
            , "workers"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "MakeEach"
      , emittedFixtureDescription = "item-labeled makeEach expansion"
      , emittedFixtureSource =
          T.unlines
            [ "kind sample(label: PortLabel) ="
            , "  -> label: Sample = @review.sample ({}) ;"
            , "let worker_names = [\"alpha\", \"beta\"];"
            , "let workers = makeEach(worker_names, sample);"
            , "workers"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "RecordScatter"
      , emittedFixtureDescription = "record-form phantom scatter (source * (a <> b))"
      , emittedFixtureSource =
          T.unlines
            [ "node source"
            , "  -> pair: Pair = @review.source ({}) ;"
            , "node a"
            , "  <- a: A ;"
            , "  -> done_a: Done = @review.a (a) ;"
            , "node b"
            , "  <- b: B ;"
            , "  -> done_b: Done = @review.b (b) ;"
            , "source * (a <> b)"
            ]
      , emittedFixtureEnv = recordScatterEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "IndexedGather"
      , emittedFixtureDescription = "indexed-product phantom gather (workers * sink)"
      , emittedFixtureSource =
          T.unlines
            [ "kind sample(label: PortLabel) ="
            , "  -> label: Sample = @review.sample ({}) ;"
            , "node sink"
            , "  <- samples: [Sample; 3] ;"
            , "  -> done: Done = @review.sink (samples) ;"
            , "let workers[] = make(3, sample);"
            , "workers * sink"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "IndexedScatter"
      , emittedFixtureDescription = "indexed-product phantom scatter (source * workers)"
      , emittedFixtureSource =
          T.unlines
            [ "node source"
            , "  -> samples: [Sample; 3] = @review.source ({}) ;"
            , "kind consume(label: PortLabel) ="
            , "  <- label: Sample ;"
            , "  -> label: Done = @review.consume (label) ;"
            , "let workers[] = make(3, consume);"
            , "source * workers"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "SelectLabel"
      , emittedFixtureDescription = "label-resolved select with a non-identity arm"
      , emittedFixtureSource =
          T.unlines
            [ "node draft_plan"
            , "  -> draft: DraftPlan = @review.plan ({}) ;"
            , "node validate_plan"
            , "  <- draft: DraftPlan ;"
            , "  -> ok: ResearchPlan | issue: PlanIssue ;"
            , "  = @review.validate_plan (draft) ;"
            , "node gather_missing_constraints"
            , "  <- issue: PlanIssue ;"
            , "  -> issue: PlanIssue = @review.gather_missing_constraints (issue) ;"
            , "node repair_plan"
            , "  <- issue: PlanIssue ;"
            , "  -> ok: ResearchPlan = @review.repair_plan (issue) ;"
            , "node publish_report"
            , "  <- ok: ResearchPlan ;"
            , "  -> report: ReportArtifactRef = @artifact.publish_report (ok) ;"
            , "draft_plan => validate_plan select("
            , "  ok: (),"
            , "  issue: (gather_missing_constraints => repair_plan)"
            , ") => publish_report"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "SelectContract"
      , emittedFixtureDescription = "contract-fallback-resolved select"
      , emittedFixtureSource =
          T.unlines
            [ "node draft_plan"
            , "  -> draft: DraftPlan = @review.plan ({}) ;"
            , "node validate_plan"
            , "  <- draft: DraftPlan ;"
            , "  -> valid: ResearchPlan | issue: PlanIssue ;"
            , "  = @review.validate_plan (draft) ;"
            , "node gather_missing_constraints"
            , "  <- issue: PlanIssue ;"
            , "  -> issue: PlanIssue = @review.gather_missing_constraints (issue) ;"
            , "node repair_plan"
            , "  <- issue: PlanIssue ;"
            , "  -> valid: ResearchPlan = @review.repair_plan (issue) ;"
            , "node publish_report"
            , "  <- valid: ResearchPlan ;"
            , "  -> report: ReportArtifactRef = @artifact.publish_report (valid) ;"
            , "draft_plan => validate_plan select("
            , "  ResearchPlan: (),"
            , "  PlanIssue: (gather_missing_constraints => repair_plan)"
            , ") => publish_report"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  ]

{- | Contract registry for the record-form phantom fixture: the nominal
record shape of @Pair@ must be declared for record @*@ lowering.
-}
recordScatterEnv :: WireCompileEnv
recordScatterEnv =
  emptyWireCompileEnv
    { wireCompileEnvContractRegistry =
        Just
          ( wireContractRegistryFromList
              [ jsonContract "A"
              , jsonContract "B"
              , jsonContract "Done"
              , (jsonContract "Pair")
                  { wireContractSpecRecordFields =
                      Just
                        ( Map.fromList
                            [ ("a", ContractId "A")
                            , ("b", ContractId "B")
                            ]
                        )
                  }
              ]
          )
    }
  where
    jsonContract contractId =
      WireContractSpec
        { wireContractSpecId = contractId
        , wireContractSpecPayloadKind = WirePayloadJson
        , wireContractSpecDescription = contractId
        , wireContractSpecRecordFields = Nothing
        , wireContractSpecSchema = Nothing
        , wireContractSpecExamples = []
        }

-- Differential oracle rendering ------------------------------------------------

{- | Fixtures covered by the differential oracle: the full emitted corpus.
Select fixtures replay at the source-visible frontier, mirroring the
validator's trace semantics: select-internal choice exits (condition-node
ports that echo a variant) are hidden from node declarations exactly as
`SelectInternalChoiceExit` hides them during validator replay, so signature
matching stays unambiguous. Exclusivity itself is the validator's and the
select theorems' job; the differential re-executes composition, not choice.
-}
differentialFixtures :: [EmittedFixture]
differentialFixtures = emittedFixtures

-- | Core expression skeleton reconstructed from a primitive trace.
data DiffExpr
  = DiffEmpty
  | DiffNode !Text
  | DiffOverlay !DiffExpr !DiffExpr
  | DiffConnect !DiffExpr !DiffExpr

{- | Replay the artifact's postorder primitive trace into an expression.
Binding annotations are skipped: they extend the used-references ledger, not
the frontier, and the differential is frontier-level by declaration.
-}
diffExprOfSteps :: [PrimitiveGraphStep] -> Either Text DiffExpr
diffExprOfSteps = go []
  where
    go stack [] =
      case stack of
        [expr] -> Right expr
        _other -> Left "primitive trace does not reduce to a single expression"
    go stack (step : rest) =
      case step of
        PrimitiveEmpty -> go (DiffEmpty : stack) rest
        PrimitiveNode ref _entries _exits ->
          go (DiffNode ref.unCircuitNodeRef : stack) rest
        PrimitiveBindingRef _binding -> go stack rest
        PrimitiveOverlay {} ->
          case stack of
            right : left : more -> go (DiffOverlay left right : more) rest
            _other -> Left "primitive trace underflow"
        PrimitiveConnect {} ->
          case stack of
            right : left : more -> go (DiffConnect left right : more) rest
            _other -> Left "primitive trace underflow"

-- | Signature rendering pair: source label and ContractId expression text.
data DiffSignature = DiffSignature
  { diffSignatureLabel :: !Text
  , diffSignatureContract :: !Text
  }

-- Replay signatures ignore exclusive-group annotations: the frontier replay
-- matches by (label, contract) exactly as the trace frames do; exclusivity is
-- validated elsewhere.
diffSignatureOf :: AdmissionBoundaryPort -> DiffSignature
diffSignatureOf row =
  DiffSignature
    { diffSignatureLabel =
        case row.admissionBoundaryLabel of
          AdmissionLabel label -> label
          AdmissionNoLabel -> row.admissionBoundaryPort
    , diffSignatureContract = renderContractExpr row.admissionBoundaryContract
    }

{- | Mirror of the validator's @SelectInternalChoiceExit@: an exit is hidden
from the visible frontier when its exclusive group is owned by a select row's
condition node and its (label, contract) echoes one of that row's variants.
-}
diffSelectInternalExit :: WireAdmissionArtifact -> AdmissionBoundaryPort -> Bool
diffSelectInternalExit artifact exit =
  any internalFor artifact.wireAdmissionSelects
  where
    internalFor selectRow =
      case exit.admissionBoundaryExclusiveGroup of
        Nothing -> False
        Just (owner, _index) ->
          owner == selectRow.selectAdmissionConditionNode
            && any
              ( \variant ->
                  variant.selectVariantPort.admissionBoundaryLabel
                    == exit.admissionBoundaryLabel
                    && variant.selectVariantPort.admissionBoundaryContract
                      == exit.admissionBoundaryContract
              )
              selectRow.selectAdmissionVariants

{- | Render a contract id, recognizing the bounded-product name shape
@[Elem;N]@ so the @ClosedBy.boundedIndexed@ constructor unifies syntactically.
-}
renderContractExpr :: Text -> Text
renderContractExpr contract =
  case boundedIndexedParts contract of
    Just (element, count) ->
      "ContractId.boundedIndexed \10216" <> leanStringLit element <> "\10217 " <> count
    Nothing ->
      "\10216" <> leanStringLit contract <> "\10217"

boundedIndexedParts :: Text -> Maybe (Text, Text)
boundedIndexedParts contract = do
  inner <- T.stripSuffix "]" =<< T.stripPrefix "[" contract
  let (element, rest) = T.breakOn ";" inner
  countText <- T.stripPrefix ";" rest
  if not (T.null element)
    && not (T.null countText)
    && T.all (`elem` ("0123456789" :: String)) countText
    then Just (element, countText)
    else Nothing

-- | Contracts the shell must declare (bounded products contribute elements).
diffDeclaredContracts :: [AdmissionBoundaryPort] -> [Text]
diffDeclaredContracts =
  foldr (addContract . (.admissionBoundaryContract)) []
  where
    addContract contract acc =
      let declared = maybe contract fst (boundedIndexedParts contract)
       in if declared `elem` acc then acc else declared : acc

diffSignatureValue :: DiffSignature -> LeanValue
diffSignatureValue signature =
  LeanAtom
    ( "\10216\10216"
        <> leanStringLit signature.diffSignatureLabel
        <> "\10217, "
        <> signature.diffSignatureContract
        <> "\10217"
    )

diffInstanceValue :: Text -> DiffSignature -> LeanValue
diffInstanceValue node signature =
  LeanAtom
    ( "\10216\10216"
        <> leanStringLit node
        <> "\10217, \10216\10216\10216"
        <> leanStringLit signature.diffSignatureLabel
        <> "\10217, "
        <> signature.diffSignatureContract
        <> "\10217\10217\10217"
    )

diffExprValue :: DiffExpr -> LeanValue
diffExprValue = \case
  DiffEmpty -> LeanAtom ".empty"
  DiffNode name -> LeanApp ".node" [anonText name]
  DiffOverlay left right -> LeanApp ".overlay" [diffExprValue left, diffExprValue right]
  DiffConnect left right -> LeanApp ".connect" [diffExprValue left, diffExprValue right]

-- | @def <header> := <value>@ with the shared width-aware layout.
diffDefLines :: Text -> LeanValue -> [Text]
diffDefLines header value =
  case renderLeanValue 2 value of
    [single]
      | T.length header + T.length single + 8 <= maxLineWidth ->
          ["def " <> header <> " := " <> single]
    valueLines ->
      ("def " <> header <> " :=") : indentFirst 2 valueLines

diffContractDefLines :: Int -> Text -> (Text, [Text])
diffContractDefLines index name =
  ( defName
  ,
    [ "/-- Declared contract `" <> name <> "` (closure row; fields are not modeled). -/"
    , "def " <> defName <> " : AcceptedRecordContractDecl where"
    , "  contract := \10216" <> leanStringLit name <> "\10217"
    , "  contractValid := by decide"
    , "  fields := []"
    , "  fieldsValid := by decide"
    , "  fieldLabelsUnique := by decide"
    ]
  )
  where
    defName = "contract" <> T.pack (show index)

diffNodeDeclLines
  :: (Int, (CircuitNodeRef, [AdmissionBoundaryPort], [AdmissionBoundaryPort]))
  -> (Text, [Text])
diffNodeDeclLines (index, (ref, entries, exits)) =
  let entrySignatures = fmap diffSignatureOf entries
      exitSignatures = fmap diffSignatureOf exits
      defName = "node" <> T.pack (show index)
   in ( defName
      , [ "/-- Accepted declaration for node `" <> ref.unCircuitNodeRef <> "`. -/"
        , "def " <> defName <> " : AcceptedNodeDecl where"
        , "  node := \10216" <> leanStringLit ref.unCircuitNodeRef <> "\10217"
        , "  nodeValid := by decide"
        ]
          <> renderArtifactField 2 ("inputs", LeanSet (fmap diffSignatureValue entrySignatures))
          <> renderArtifactField
            2
            ("outputs", LeanList (fmap (\sig -> LeanApp ".single" [diffSignatureValue sig]) exitSignatures))
          <> [ "  inputPortsValid := by decide"
             , "  outputShapesAdmissible := by decide"
             , "  outputPortsListLabelsUnique := by decide"
             , "  inputLabelsUnique := by decide"
             , "  body := .corePure"
             , "  bodyLocalValid := by decide"
             ]
      )

diffShellLines :: Bool -> [Text] -> [Text] -> [Text]
diffShellLines hasBoundedContracts contractNames nodeNames =
  [ "/-- Module shell assembled from the artifact's node rows. -/"
  , "def shell : AdmittedModuleShell where"
  ]
    <> renderArtifactField 2 ("contracts", LeanList (fmap LeanAtom contractNames))
    <> ["  contractsUnique := by decide", "  kinds := []", "  kindsUnique := by decide"]
    <> renderArtifactField 2 ("nodes", LeanList (fmap LeanAtom nodeNames))
    <> [ "  nodesUnique := by decide"
       , "  graphs := []"
       , "  graphsUnique := by decide"
       , "  graphsValid := fun _ hGraph => nomatch hGraph"
       , "  recordFieldContractsClosed := by"
       , "    intro contract hContract"
       , "    fin_cases hContract <;> exact fun _ hField => nomatch hField"
       , "  nodeContractsClosed := by"
       , "    intro node hNode"
       , "    fin_cases hNode <;>"
       , "      refine \10216fun port hPort => ?_, fun port hPort => ?_\10217 <;>"
       , "        fin_cases hPort <;>"
       ]
    <> ( if hasBoundedContracts
           then
             [ "          first"
             , "            | exact ContractId.ClosedBy.declared (by decide)"
             , "            | exact ContractId.ClosedBy.boundedIndexed _ (by decide)"
             ]
           else ["          exact ContractId.ClosedBy.declared (by decide)"]
       )
    <> [ "  kindContractsClosed := fun _ hKind => nomatch hKind"
       , "  graphRefsClosed := fun _ hGraph => nomatch hGraph"
       ]

-- | Render the differential module for one fixture's emitted artifact.
renderDifferentialModuleText :: EmittedFixture -> WireAdmissionArtifact -> Either Text Text
renderDifferentialModuleText fixture artifact = do
  expr <- diffExprOfSteps artifact.wireAdmissionPrimitiveSteps
  let visibleExits = filter (not . diffSelectInternalExit artifact)
      nodeRows =
        [ (ref, entries, visibleExits exits)
        | PrimitiveNode ref entries exits <- artifact.wireAdmissionPrimitiveSteps
        ]
      nodeDecls = fmap diffNodeDeclLines (zip [0 ..] nodeRows)
      instanceOf row =
        diffInstanceValue row.admissionBoundaryNode.unCircuitNodeRef (diffSignatureOf row)
      entryInstances = fmap instanceOf artifact.wireAdmissionEntries
      exitInstances = fmap instanceOf artifact.wireAdmissionExits
      allRows = concatMap (\(_ref, entries, exits) -> entries <> exits) nodeRows
      contractDefs = zipWith diffContractDefLines [0 ..] (diffDeclaredContracts allRows)
      namespaceName = "Differential" <> fixture.emittedFixtureSlug
  Right . T.unlines $
    [ "import Cortex.Wire.ElaborationIRDecide"
    , "import Cortex.Wire.GraphElaborationExec"
    , "import Mathlib.Tactic.FinCases"
    , ""
    , "/-!"
    , "## Overview"
    , ""
    , "Differential oracle for the `" <> fixture.emittedFixtureSlug <> "` fixture: the"
    , "executable admission kernel replays the compiler's composition (reconstructed"
    , "from the emitted artifact's primitive trace, binding annotations skipped)"
    , "against a module shell assembled from the artifact's node rows, and must land"
    , "on the exposed boundary the compiler recorded."
    , ""
    , "GENERATED FILE - do not edit by hand. Regenerated by"
    , "`just wire-lean-fixtures`; the Haskell test suite fails on drift."
    , "-/"
    , ""
    , "namespace Cortex.Wire"
    , "namespace AdmissionArtifact"
    , "namespace " <> namespaceName
    , ""
    , "open Cortex.Wire.ElaborationIR"
    , ""
    ]
      <> concatMap (\(_name, defLines) -> defLines <> [""]) contractDefs
      <> concatMap (\(_name, defLines) -> defLines <> [""]) nodeDecls
      <> diffShellLines
        (any (\row -> isJust (boundedIndexedParts row.admissionBoundaryContract)) allRows)
        (fmap fst contractDefs)
        (fmap fst nodeDecls)
      <> [""]
      <> [ "/-- Core expression reconstructed from the artifact's primitive trace"
         , "(binding annotations skipped; the differential is frontier-level). -/"
         ]
      <> diffDefLines "expr : GraphExpr" (diffExprValue expr)
      <> [""]
      <> ["/-- Output frontier the compiler exposed for this fixture. -/"]
      <> diffDefLines
        "expectedOutputs : Finset (SourcePortInstance NodeId OutputPortSignature)"
        (LeanSet exitInstances)
      <> [""]
      <> ["/-- Input frontier the compiler exposed for this fixture. -/"]
      <> diffDefLines
        "expectedInputs : Finset (SourcePortInstance NodeId InputPortSignature)"
        (LeanSet entryInstances)
      <> [ ""
         , "-- The kernel replays the compiler's composition onto the same boundary."
         , "#guard"
         , "  match CertifiedGraph.elaborate shell expr with"
         , "  | .ok result =>"
         , "      decide (result.val.object.graph.exposedOutputs = expectedOutputs) &&"
         , "        decide (result.val.object.graph.exposedInputs = expectedInputs)"
         , "  | .error _ => false"
         , ""
         , "end " <> namespaceName
         , "end AdmissionArtifact"
         , "end Cortex.Wire"
         ]

renderDifferentialUmbrellaModule :: [EmittedFixture] -> Text
renderDifferentialUmbrellaModule fixtures =
  T.unlines
    ( fmap
        ( \fixture ->
            "import Cortex.Wire.AdmissionArtifact.Differential." <> fixture.emittedFixtureSlug
        )
        fixtures
        <> [ ""
           , "/-!"
           , "## Overview"
           , ""
           , "Umbrella for the generated differential-oracle modules: per fixture, the"
           , "executable admission kernel replays the compiler's composition and must"
           , "land on the same exposed boundary the artifact records. Regenerate with"
           , "`just wire-lean-fixtures`; the Haskell test suite fails on drift."
           , "-/"
           ]
    )
