{- |
Module      : Cortex.Wire.LeanFixture
Description : Render emitted Wire admission artifacts as Lean fixture modules.
Copyright   : (c) 2026 Digimuoto Oy
License     : Apache-2.0
Maintainer  : julius.koskela@digimuoto.com
Stability   : experimental

Renders a compiled circuit's 'WireAdmissionArtifact' as Lean source in the
shape of @theory/Cortex/Wire/AdmissionArtifact/EmittedFixture.lean@: a value
definition, a @#guard@ running the Lean-owned executable validator, and a
soundness theorem discharged by @native_decide@. The generated modules are
checked into @theory/@ so @just lean-check@ validates real compiler output;
the Haskell test suite re-renders each fixture and fails on drift.
-}
module Cortex.Wire.LeanFixture
  ( EmittedFixture (..)
  , emittedFixtures
  , emittedFixtureModuleName
  , emittedFixtureNamespace
  , renderEmittedFixtureModule
  , renderEmittedUmbrellaModule
  , compiledWireAdmissionArtifact
  ) where

import Data.Aeson qualified as Aeson
import Data.Aeson.Key qualified as AesonKey
import Data.Aeson.KeyMap qualified as AesonKeyMap
import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as T
import Numeric.Natural (Natural)

import Cortex.Wire.AST (Connection (..), EndpointRef (..))
import Cortex.Wire.AST qualified as WireCore
import Cortex.Wire.AdmissionArtifact
import Cortex.Wire.Circuit.Compiled (CompiledCircuit (..))
import Cortex.Wire.Circuit.IR (CircuitNodeRef (..))
import Cortex.Wire.Compile (compileWireFragmentTextWithEnv)
import Cortex.Wire.Contracts
  ( WireCompileEnv (..)
  , WireContractSpec (..)
  , emptyWireCompileEnv
  , wireContractRegistryFromList
  )
import Cortex.Wire.Syntax (ContractId (..))
import Cortex.Wire.Value (WirePayloadKind (..))

-- | A Wire source fixture whose emitted artifact becomes a Lean module.
data EmittedFixture = EmittedFixture
  { emittedFixtureSlug :: !Text
  -- ^ Lean module suffix, e.g. @Chain@ for @...Emitted.Chain@.
  , emittedFixtureDescription :: !Text
  , emittedFixtureSource :: !Text
  , emittedFixtureEnv :: !WireCompileEnv
  {- ^ Compile environment; record-form phantom fixtures need a contract
  registry that declares their nominal record shape.
  -}
  }

emittedFixtureModuleName :: EmittedFixture -> Text
emittedFixtureModuleName fixture =
  "Cortex.Wire.AdmissionArtifact.Emitted." <> fixture.emittedFixtureSlug

emittedFixtureNamespace :: EmittedFixture -> Text
emittedFixtureNamespace fixture =
  "Emitted" <> fixture.emittedFixtureSlug

-- | Extract the admission artifact a compilation attached to its circuit.
compiledWireAdmissionArtifact :: CompiledCircuit -> Maybe WireAdmissionArtifact
compiledWireAdmissionArtifact compiled =
  case compiled.compiledCircuitMetadata of
    Aeson.Object obj -> do
      admission <- AesonKeyMap.lookup (AesonKey.fromText wireAdmissionMetadataKey) obj
      case Aeson.fromJSON admission of
        Aeson.Success artifact -> Just artifact
        Aeson.Error _message -> Nothing
    _ -> Nothing

-- | Compile a fixture source and render its artifact as a Lean module.
renderEmittedFixtureModule :: EmittedFixture -> Either WireCore.WireError Text
renderEmittedFixtureModule fixture = do
  compiled <- compileWireFragmentTextWithEnv fixture.emittedFixtureEnv fixture.emittedFixtureSource
  artifact <- case compiledWireAdmissionArtifact compiled of
    Just artifact -> Right artifact
    Nothing ->
      Left
        ( WireCore.WireParseError
            ("compiled fixture carries no admission artifact: " <> fixture.emittedFixtureSlug)
        )
  Right (renderFixtureModuleText fixture artifact)

-- | Umbrella module importing every generated fixture module.
renderEmittedUmbrellaModule :: [EmittedFixture] -> Text
renderEmittedUmbrellaModule fixtures =
  T.unlines
    ( fmap (\fixture -> "import " <> emittedFixtureModuleName fixture) fixtures
        <> [ ""
           , "/-!"
           , "## Overview"
           , ""
           , "Umbrella for the generated emitted-artifact fixtures. Each import is a"
           , "Lean module generated from a compiled Wire fixture by"
           , "`Cortex.Wire.LeanFixture`; regenerate with `just wire-lean-fixtures`."
           , "The Haskell test suite fails when any generated module drifts from the"
           , "current compiler output."
           , "-/"
           ]
    )

renderFixtureModuleText :: EmittedFixture -> WireAdmissionArtifact -> Text
renderFixtureModuleText fixture artifact =
  T.unlines
    ( [ "import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck"
      , ""
      , "/-!"
      , "## Overview"
      , ""
      , "Wire admission artifact emitted by the Haskell compiler for the"
      , T.concat ["`", fixture.emittedFixtureSlug, "` fixture: ", fixture.emittedFixtureDescription, "."]
      , ""
      , "GENERATED FILE - do not edit by hand. Regenerated by"
      , "`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test"
      , "suite fails when this file drifts from the current compiler output."
      , "`validatorReadyCheck_soundness` lifts the build-time boolean check below to"
      , "`WireAdmissionArtifact.Sound` for this artifact."
      , "-/"
      , ""
      , "namespace Cortex.Wire"
      , "namespace AdmissionArtifact"
      , "namespace " <> emittedFixtureNamespace fixture
      , ""
      ]
        <> artifactDocComment fixture.emittedFixtureDescription
        <> [ "def artifact : WireAdmissionArtifact where"
           ]
        <> concatMap (renderArtifactField 2) (artifactFields artifact)
        <> [ ""
           , "-- The Lean-owned executable validator accepts the emitted artifact."
           , "#guard artifact.validatorReadyCheck"
           , ""
           , "/-- The accepted artifact satisfies the proof-facing soundness contract. -/"
           , "theorem artifact_sound : artifact.Sound :="
           , "  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)"
           , ""
           , "end " <> emittedFixtureNamespace fixture
           , "end AdmissionArtifact"
           , "end Cortex.Wire"
           ]
    )

-- | Docstring for the artifact definition, wrapped under the lint width.
artifactDocComment :: Text -> [Text]
artifactDocComment description
  | T.length oneLine <= maxLineWidth = [oneLine]
  | otherwise =
      [ "/-- Emitted admission artifact for the"
      , description <> " fixture. -/"
      ]
  where
    oneLine = "/-- Emitted admission artifact for the " <> description <> " fixture. -/"

renderArtifactField :: Int -> (Text, LeanValue) -> [Text]
renderArtifactField indent (name, value) =
  case renderLeanValue (indent + 2) value of
    [single]
      | indent + T.length name + 4 + T.length single <= maxLineWidth ->
          [spaces indent <> name <> " := " <> single]
    valueLines ->
      (spaces indent <> name <> " :=")
        : indentFirst (indent + 2) valueLines

artifactFields :: WireAdmissionArtifact -> [(Text, LeanValue)]
artifactFields artifact =
  [ ("schemaVersion", naturalValue artifact.wireAdmissionSchemaVersion)
  , ("nodes", LeanList (fmap nodeRefValue artifact.wireAdmissionNodes))
  , ("bindingRefs", LeanList (fmap anonText artifact.wireAdmissionBindingRefs))
  , ("entries", LeanList (fmap boundaryPortValue artifact.wireAdmissionEntries))
  , ("exits", LeanList (fmap boundaryPortValue artifact.wireAdmissionExits))
  , ("connections", LeanList (fmap rawConnectionValue artifact.wireAdmissionConnections))
  , ("primitiveSteps", LeanList (fmap primitiveStepValue artifact.wireAdmissionPrimitiveSteps))
  , ("generatedForms", LeanList (fmap generatedFormValue artifact.wireAdmissionGeneratedForms))
  , ("phantomAdapters", LeanList (fmap phantomAdapterValue artifact.wireAdmissionPhantomAdapters))
  , ("selects", LeanList (fmap selectValue artifact.wireAdmissionSelects))
  ]

-- Value translation ---------------------------------------------------------

nodeRefValue :: CircuitNodeRef -> LeanValue
nodeRefValue ref = anonText ref.unCircuitNodeRef

anonText :: Text -> LeanValue
anonText text = LeanAtom ("\10216" <> leanStringLit text <> "\10217")

naturalValue :: Natural -> LeanValue
naturalValue = LeanAtom . T.pack . show

boundaryPortValue :: AdmissionBoundaryPort -> LeanValue
boundaryPortValue boundary =
  LeanRecord
    [ ("node", nodeRefValue boundary.admissionBoundaryNode)
    , ("port", anonText boundary.admissionBoundaryPort)
    , ("contract", anonText boundary.admissionBoundaryContract)
    , ("label", portLabelValue boundary.admissionBoundaryLabel)
    , ("exclusiveGroup", exclusiveGroupValue boundary.admissionBoundaryExclusiveGroup)
    ]

portLabelValue :: AdmissionPortLabel -> LeanValue
portLabelValue = \case
  AdmissionNoLabel -> LeanAtom ".noLabel"
  AdmissionLabel label -> LeanApp ".label" [anonText label]

exclusiveGroupValue :: Maybe (CircuitNodeRef, Natural) -> LeanValue
exclusiveGroupValue = \case
  Nothing -> LeanAtom "none"
  Just (owner, groupIndex) ->
    LeanApp "some" [LeanTuple [nodeRefValue owner, naturalValue groupIndex]]

rawConnectionValue :: Connection -> LeanValue
rawConnectionValue connection =
  LeanRecord
    [ ("fromEndpoint", endpointValue connection.connectionFrom)
    , ("toEndpoint", endpointValue connection.connectionTo)
    ]

endpointValue :: EndpointRef -> LeanValue
endpointValue endpoint =
  LeanRecord
    [ ("node", nodeRefValue endpoint.endpointNodeRef)
    ,
      ( "port"
      , case endpoint.endpointPortName of
          Nothing -> LeanAtom "none"
          Just port -> LeanApp "some" [anonText port]
      )
    ]

matchedPairValue :: AdmissionConnection -> LeanValue
matchedPairValue connection =
  LeanRecord
    [ ("fromPort", boundaryPortValue connection.admissionConnectionFrom)
    , ("toPort", boundaryPortValue connection.admissionConnectionTo)
    ]

primitiveStepValue :: PrimitiveGraphStep -> LeanValue
primitiveStepValue = \case
  PrimitiveEmpty ->
    LeanAtom ".empty"
  PrimitiveNode node entries exits ->
    LeanApp
      ".node"
      [ nodeRefValue node
      , LeanList (fmap boundaryPortValue entries)
      , LeanList (fmap boundaryPortValue exits)
      ]
  PrimitiveBindingRef binding ->
    LeanApp ".bindingRef" [anonText binding]
  PrimitiveOverlay leftNodes rightNodes leftBindings rightBindings ->
    LeanApp
      ".overlay"
      [ LeanList (fmap nodeRefValue leftNodes)
      , LeanList (fmap nodeRefValue rightNodes)
      , LeanList (fmap anonText leftBindings)
      , LeanList (fmap anonText rightBindings)
      ]
  PrimitiveConnect leftExits rightEntries matchedPairs unmatchedLeftExits unmatchedRightEntries ->
    LeanApp
      ".connect"
      [ LeanList (fmap boundaryPortValue leftExits)
      , LeanList (fmap boundaryPortValue rightEntries)
      , LeanList (fmap matchedPairValue matchedPairs)
      , LeanList (fmap boundaryPortValue unmatchedLeftExits)
      , LeanList (fmap boundaryPortValue unmatchedRightEntries)
      ]

generatedFormValue :: GeneratedFormArtifact -> LeanValue
generatedFormValue form =
  LeanRecord
    [
      ( "kind"
      , case form.generatedFormKind of
          GeneratedMake -> LeanAtom ".make"
          GeneratedMakeEach -> LeanAtom ".makeEach"
      )
    , ("kindName", anonText form.generatedFormKindName)
    , ("binding", anonText form.generatedFormBinding)
    , ("sourceChildren", LeanList (fmap generatedChildSourceValue form.generatedFormSourceChildren))
    , ("usedChildren", LeanList (fmap generatedChildValue form.generatedFormUsedChildren))
    ]

generatedChildSourceValue :: GeneratedChildSourceArtifact -> LeanValue
generatedChildSourceValue child =
  LeanRecord
    [ ("node", nodeRefValue child.generatedSourceChildNode)
    , ("label", anonText child.generatedSourceChildLabel)
    ,
      ( "value"
      , case child.generatedSourceChildValue of
          Nothing -> LeanAtom "none"
          Just value -> LeanApp "some" [staticValueValue value]
      )
    ]

staticValueValue :: AdmissionStaticValue -> LeanValue
staticValueValue = \case
  AdmissionStaticString text -> LeanApp ".string" [LeanAtom (leanStringLit text)]
  AdmissionStaticBool boolValue ->
    LeanApp ".bool" [LeanAtom (if boolValue then "true" else "false")]
  AdmissionStaticNat natValue -> LeanApp ".nat" [naturalValue natValue]
  AdmissionStaticList values -> LeanApp ".list" [LeanList (fmap staticValueValue values)]
  AdmissionStaticRecord fields ->
    LeanApp
      ".record"
      [ LeanList
          ( fmap
              ( \field ->
                  LeanTuple
                    [ anonText field.admissionStaticFieldLabel
                    , staticValueValue field.admissionStaticFieldValue
                    ]
              )
              fields
          )
      ]

generatedChildValue :: GeneratedChildArtifact -> LeanValue
generatedChildValue child =
  LeanRecord
    [ ("node", nodeRefValue child.generatedChildNode)
    , ("label", anonText child.generatedChildLabel)
    , ("outputs", LeanList (fmap boundaryPortValue child.generatedChildOutputs))
    , ("inputs", LeanList (fmap boundaryPortValue child.generatedChildInputs))
    ]

phantomAdapterValue :: PhantomAdapterArtifact -> LeanValue
phantomAdapterValue adapter =
  LeanRecord
    [
      ( "direction"
      , case adapter.phantomAdapterDirection of
          PhantomGather -> LeanAtom ".gather"
          PhantomScatter -> LeanAtom ".scatter"
      )
    , ("node", nodeRefValue adapter.phantomAdapterNode)
    , ("productShape", productShapeValue adapter.phantomAdapterProductShape)
    , ("singular", boundaryPortValue adapter.phantomAdapterSingular)
    , ("multi", LeanList (fmap boundaryPortValue adapter.phantomAdapterMulti))
    , ("leftBulk", LeanList (fmap matchedPairValue adapter.phantomAdapterLeftBulk))
    , ("rightBulk", LeanList (fmap matchedPairValue adapter.phantomAdapterRightBulk))
    ]

productShapeValue :: ProductShapeArtifact -> LeanValue
productShapeValue = \case
  ProductRecord contract fields ->
    LeanApp
      ".record"
      [ anonText contract
      , LeanList
          (fmap (\(label, fieldContract) -> LeanTuple [anonText label, anonText fieldContract]) fields)
      ]
  ProductIndexed elementContract count ->
    LeanApp ".indexed" [anonText elementContract, naturalValue count]

selectValue :: SelectAdmissionArtifact -> LeanValue
selectValue select =
  LeanRecord
    [ ("owner", nodeRefValue select.selectAdmissionOwner)
    , ("variants", LeanList (fmap selectVariantValue select.selectAdmissionVariants))
    , ("arms", LeanList (fmap selectArmValue select.selectAdmissionArms))
    , ("conditionNode", nodeRefValue select.selectAdmissionConditionNode)
    ]

selectVariantValue :: SelectVariantArtifact -> LeanValue
selectVariantValue variant =
  LeanRecord
    [ ("key", anonText variant.selectVariantKey)
    , ("port", boundaryPortValue variant.selectVariantPort)
    ]

selectArmValue :: SelectArmAdmissionArtifact -> LeanValue
selectArmValue arm =
  LeanRecord
    [ ("sourceIndex", naturalValue arm.selectArmSourceIndex)
    , ("sourceKey", anonText arm.selectArmSourceKey)
    , ("canonicalKey", anonText arm.selectArmCanonicalKey)
    ,
      ( "mode"
      , case arm.selectArmResolutionMode of
          SelectResolvedByLabel -> LeanAtom ".resolvedByLabel"
          SelectResolvedByContract -> LeanAtom ".resolvedByContract"
      )
    , ("bodyNodes", LeanList (fmap nodeRefValue arm.selectArmBodyNodes))
    , ("bodyEntries", LeanList (fmap boundaryPortValue arm.selectArmBodyEntries))
    , ("bodyExits", LeanList (fmap boundaryPortValue arm.selectArmBodyExits))
    ]

-- Lean value layout ----------------------------------------------------------

-- | Lean term skeleton: enough structure for artifact literals.
data LeanValue
  = LeanAtom !Text
  | LeanApp !Text ![LeanValue]
  | LeanList ![LeanValue]
  | LeanTuple ![LeanValue]
  | LeanRecord ![(Text, LeanValue)]

maxLineWidth :: Int
maxLineWidth = 96

spaces :: Int -> Text
spaces n = T.replicate n " "

leanString :: Text -> Text
leanString = T.concatMap escape
  where
    escape = \case
      '"' -> "\\\""
      '\\' -> "\\\\"
      '\n' -> "\\n"
      other -> T.singleton other

leanStringLit :: Text -> Text
leanStringLit text = "\"" <> leanString text <> "\""

inlineLeanValue :: LeanValue -> Text
inlineLeanValue = \case
  LeanAtom text -> text
  LeanApp constructor args ->
    T.unwords (constructor : fmap inlineArgument args)
  LeanList [] -> "[]"
  LeanList values -> "[" <> T.intercalate ", " (fmap inlineLeanValue values) <> "]"
  LeanTuple values -> "(" <> T.intercalate ", " (fmap inlineLeanValue values) <> ")"
  LeanRecord fields ->
    "{ "
      <> T.intercalate ", " (fmap (\(name, value) -> name <> " := " <> inlineLeanValue value) fields)
      <> " }"

-- Constructor arguments that are themselves applications need parentheses.
inlineArgument :: LeanValue -> Text
inlineArgument value =
  case value of
    LeanApp _ (_ : _) -> "(" <> inlineLeanValue value <> ")"
    _ -> inlineLeanValue value

{- | Render a value at a column. The first line carries no indentation (the
caller splices it after its own prefix); continuation lines carry absolute
indentation relative to the given column.
-}
renderLeanValue :: Int -> LeanValue -> [Text]
renderLeanValue indent value
  | indent + T.length inline <= maxLineWidth = [inline]
  | otherwise = renderMultiline indent value
  where
    inline = inlineLeanValue value

renderMultiline :: Int -> LeanValue -> [Text]
renderMultiline indent = \case
  LeanAtom text ->
    [text]
  LeanApp constructor args ->
    constructor
      : concatMap (indentFirst (indent + 4) . renderLeanValue (indent + 4)) args
  LeanList [] ->
    ["[]"]
  LeanList values ->
    blockLines indent "[ " ", " "]" (fmap (renderLeanValue (indent + 2)) values)
  LeanTuple values ->
    blockLines indent "( " ", " ")" (fmap (renderLeanValue (indent + 2)) values)
  LeanRecord fields ->
    blockLines indent "{ " ", " "}" (fmap (renderRecordField indent) fields)

renderRecordField :: Int -> (Text, LeanValue) -> [Text]
renderRecordField indent (name, value) =
  case renderLeanValue (indent + 2) value of
    [single]
      | indent + 2 + T.length name + 4 + T.length single <= maxLineWidth ->
          [name <> " := " <> single]
    _multi ->
      (name <> " :=")
        : indentFirst (indent + 4) (renderLeanValue (indent + 4) value)

{- | Assemble bracketed multi-element layout: the opener fuses with the first
element, separators with each subsequent element, closer on its own line.
-}
blockLines :: Int -> Text -> Text -> Text -> [[Text]] -> [Text]
blockLines indent opener separator closer elements =
  case elements of
    [] ->
      [opener <> closer]
    firstElement : restElements ->
      attach opener firstElement
        <> concatMap (fmap (spaces indent <>) . attach' separator) restElements
        <> [spaces indent <> closer]
  where
    attach prefix element =
      case element of
        [] -> [prefix]
        firstLine : restLines -> (prefix <> firstLine) : restLines
    -- Continuation lines after the first already carry absolute indentation.
    attach' prefix element =
      case element of
        [] -> [prefix]
        firstLine : restLines ->
          (prefix <> firstLine) : fmap (T.drop indent) restLines

indentFirst :: Int -> [Text] -> [Text]
indentFirst indent = \case
  [] -> []
  firstLine : restLines -> (spaces indent <> firstLine) : restLines

-- Fixture corpus -------------------------------------------------------------

{- | Representative Wire programs covering every artifact component: primitive
chain, generated forms, phantom adapters in both directions and shapes, and
both select resolution modes. Sources mirror the CompileSpec fixtures of the
same names.
-}
emittedFixtures :: [EmittedFixture]
emittedFixtures =
  [ EmittedFixture
      { emittedFixtureSlug = "Chain"
      , emittedFixtureDescription = "labeled primitive chain (planner => analyst)"
      , emittedFixtureSource =
          T.unlines
            [ "node planner"
            , "  -> plan: PlannerOutput = @review.planner ({}) ;"
            , "node analyst"
            , "  <- plan: PlannerOutput ;"
            , "  -> analysis: AnalysisFragment = @review.analyst (plan) ;"
            , "planner => analyst"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "Make"
      , emittedFixtureDescription = "bounded make expansion (make(3, sample))"
      , emittedFixtureSource =
          T.unlines
            [ "kind sample(label: PortLabel) ="
            , "  -> label: Sample = @review.sample ({}) ;"
            , "let workers = make(3, sample);"
            , "workers"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "MakeEach"
      , emittedFixtureDescription = "item-labeled makeEach expansion"
      , emittedFixtureSource =
          T.unlines
            [ "kind sample(label: PortLabel) ="
            , "  -> label: Sample = @review.sample ({}) ;"
            , "let worker_names = [\"alpha\", \"beta\"];"
            , "let workers = makeEach(worker_names, sample);"
            , "workers"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "RecordScatter"
      , emittedFixtureDescription = "record-form phantom scatter (source * (a <> b))"
      , emittedFixtureSource =
          T.unlines
            [ "node source"
            , "  -> pair: Pair = @review.source ({}) ;"
            , "node a"
            , "  <- a: A ;"
            , "  -> done_a: Done = @review.a (a) ;"
            , "node b"
            , "  <- b: B ;"
            , "  -> done_b: Done = @review.b (b) ;"
            , "source * (a <> b)"
            ]
      , emittedFixtureEnv = recordScatterEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "IndexedGather"
      , emittedFixtureDescription = "indexed-product phantom gather (workers * sink)"
      , emittedFixtureSource =
          T.unlines
            [ "kind sample(label: PortLabel) ="
            , "  -> label: Sample = @review.sample ({}) ;"
            , "node sink"
            , "  <- samples: [Sample; 3] ;"
            , "  -> done: Done = @review.sink (samples) ;"
            , "let workers[] = make(3, sample);"
            , "workers * sink"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "IndexedScatter"
      , emittedFixtureDescription = "indexed-product phantom scatter (source * workers)"
      , emittedFixtureSource =
          T.unlines
            [ "node source"
            , "  -> samples: [Sample; 3] = @review.source ({}) ;"
            , "kind consume(label: PortLabel) ="
            , "  <- label: Sample ;"
            , "  -> label: Done = @review.consume (label) ;"
            , "let workers[] = make(3, consume);"
            , "source * workers"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "SelectLabel"
      , emittedFixtureDescription = "label-resolved select with a non-identity arm"
      , emittedFixtureSource =
          T.unlines
            [ "node draft_plan"
            , "  -> draft: DraftPlan = @review.plan ({}) ;"
            , "node validate_plan"
            , "  <- draft: DraftPlan ;"
            , "  -> ok: ResearchPlan | issue: PlanIssue ;"
            , "  = @review.validate_plan (draft) ;"
            , "node gather_missing_constraints"
            , "  <- issue: PlanIssue ;"
            , "  -> issue: PlanIssue = @review.gather_missing_constraints (issue) ;"
            , "node repair_plan"
            , "  <- issue: PlanIssue ;"
            , "  -> ok: ResearchPlan = @review.repair_plan (issue) ;"
            , "node publish_report"
            , "  <- ok: ResearchPlan ;"
            , "  -> report: ReportArtifactRef = @artifact.publish_report (ok) ;"
            , "draft_plan => validate_plan select("
            , "  ok: (),"
            , "  issue: (gather_missing_constraints => repair_plan)"
            , ") => publish_report"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  , EmittedFixture
      { emittedFixtureSlug = "SelectContract"
      , emittedFixtureDescription = "contract-fallback-resolved select"
      , emittedFixtureSource =
          T.unlines
            [ "node draft_plan"
            , "  -> draft: DraftPlan = @review.plan ({}) ;"
            , "node validate_plan"
            , "  <- draft: DraftPlan ;"
            , "  -> valid: ResearchPlan | issue: PlanIssue ;"
            , "  = @review.validate_plan (draft) ;"
            , "node gather_missing_constraints"
            , "  <- issue: PlanIssue ;"
            , "  -> issue: PlanIssue = @review.gather_missing_constraints (issue) ;"
            , "node repair_plan"
            , "  <- issue: PlanIssue ;"
            , "  -> valid: ResearchPlan = @review.repair_plan (issue) ;"
            , "node publish_report"
            , "  <- valid: ResearchPlan ;"
            , "  -> report: ReportArtifactRef = @artifact.publish_report (valid) ;"
            , "draft_plan => validate_plan select("
            , "  ResearchPlan: (),"
            , "  PlanIssue: (gather_missing_constraints => repair_plan)"
            , ") => publish_report"
            ]
      , emittedFixtureEnv = emptyWireCompileEnv
      }
  ]

{- | Contract registry for the record-form phantom fixture: the nominal
record shape of @Pair@ must be declared for record @*@ lowering.
-}
recordScatterEnv :: WireCompileEnv
recordScatterEnv =
  emptyWireCompileEnv
    { wireCompileEnvContractRegistry =
        Just
          ( wireContractRegistryFromList
              [ jsonContract "A"
              , jsonContract "B"
              , jsonContract "Done"
              , (jsonContract "Pair")
                  { wireContractSpecRecordFields =
                      Just
                        ( Map.fromList
                            [ ("a", ContractId "A")
                            , ("b", ContractId "B")
                            ]
                        )
                  }
              ]
          )
    }
  where
    jsonContract contractId =
      WireContractSpec
        { wireContractSpecId = contractId
        , wireContractSpecPayloadKind = WirePayloadJson
        , wireContractSpecDescription = contractId
        , wireContractSpecRecordFields = Nothing
        , wireContractSpecSchema = Nothing
        , wireContractSpecExamples = []
        }
