import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck

/-!
## Overview

Wire admission artifact emitted by the Haskell compiler for the
`Chain` fixture: labeled primitive chain (planner => analyst).

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current compiler output.
`validatorReadyCheck_soundness` lifts the build-time boolean check below to
`WireAdmissionArtifact.Sound` for this artifact.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace EmittedChain

/-- Emitted admission artifact for the labeled primitive chain (planner => analyst) fixture. -/
def artifact : WireAdmissionArtifact where
  schemaVersion := 4
  closureMode := .openFragment
  nodes := [⟨"analyst"⟩, ⟨"planner"⟩]
  bindingRefs := []
  entries := []
  exits :=
    [ { node := ⟨"analyst"⟩
      , port := ⟨"analysis"⟩
      , contract := ⟨"AnalysisFragment"⟩
      , label := .label ⟨"analysis"⟩
      , exclusiveGroup := none
      }
    ]
  connections :=
    [ { fromEndpoint := { node := ⟨"planner"⟩, port := some ⟨"plan"⟩ }
      , toEndpoint := { node := ⟨"analyst"⟩, port := some ⟨"plan"⟩ }
      }
    ]
  primitiveSteps :=
    [ .node
          ⟨"planner"⟩
          []
          [ { node := ⟨"planner"⟩
            , port := ⟨"plan"⟩
            , contract := ⟨"PlannerOutput"⟩
            , label := .label ⟨"plan"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"analyst"⟩
          [ { node := ⟨"analyst"⟩
            , port := ⟨"plan"⟩
            , contract := ⟨"PlannerOutput"⟩
            , label := .label ⟨"plan"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"analyst"⟩
            , port := ⟨"analysis"⟩
            , contract := ⟨"AnalysisFragment"⟩
            , label := .label ⟨"analysis"⟩
            , exclusiveGroup := none
            }
          ]
    , .connect
          [ { node := ⟨"planner"⟩
            , port := ⟨"plan"⟩
            , contract := ⟨"PlannerOutput"⟩
            , label := .label ⟨"plan"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"analyst"⟩
            , port := ⟨"plan"⟩
            , contract := ⟨"PlannerOutput"⟩
            , label := .label ⟨"plan"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"planner"⟩
                , port := ⟨"plan"⟩
                , contract := ⟨"PlannerOutput"⟩
                , label := .label ⟨"plan"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"analyst"⟩
                , port := ⟨"plan"⟩
                , contract := ⟨"PlannerOutput"⟩
                , label := .label ⟨"plan"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    ]
  generatedForms := []
  phantomAdapters := []
  selects := []
  endpointUses :=
    { inputUses :=
        [ { port :=
              { node := ⟨"analyst"⟩
              , port := ⟨"plan"⟩
              , contract := ⟨"PlannerOutput"⟩
              , label := .label ⟨"plan"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .producedByEdge
                  { node := ⟨"planner"⟩
                  , port := ⟨"plan"⟩
                  , contract := ⟨"PlannerOutput"⟩
                  , label := .label ⟨"plan"⟩
                  , exclusiveGroup := none
                  }
          }
        ]
    , outputUses :=
        [ { port :=
              { node := ⟨"planner"⟩
              , port := ⟨"plan"⟩
              , contract := ⟨"PlannerOutput"⟩
              , label := .label ⟨"plan"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .consumedByEdge
                  { node := ⟨"analyst"⟩
                  , port := ⟨"plan"⟩
                  , contract := ⟨"PlannerOutput"⟩
                  , label := .label ⟨"plan"⟩
                  , exclusiveGroup := none
                  }
          }
        , { port :=
              { node := ⟨"analyst"⟩
              , port := ⟨"analysis"⟩
              , contract := ⟨"AnalysisFragment"⟩
              , label := .label ⟨"analysis"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        ]
    }

-- The Lean-owned executable validator accepts the emitted artifact.
#guard artifact.validatorReadyCheck

/-- The accepted artifact satisfies the proof-facing soundness contract. -/
theorem artifact_sound : artifact.Sound :=
  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)

end EmittedChain
end AdmissionArtifact
end Cortex.Wire
