import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck

/-!
## Overview

Wire admission artifact emitted by the Haskell compiler for the
`IndexedGather` fixture: indexed-product phantom gather (workers * sink).

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current compiler output.
`validatorReadyCheck_soundness` lifts the build-time boolean check below to
`WireAdmissionArtifact.Sound` for this artifact.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace EmittedIndexedGather

/-- Emitted admission artifact for the
indexed-product phantom gather (workers * sink) fixture. -/
def artifact : WireAdmissionArtifact where
  schemaVersion := 3
  nodes :=
    [⟨"__star:gather:b30635591d8b"⟩, ⟨"sink"⟩, ⟨"workers_0"⟩, ⟨"workers_1"⟩, ⟨"workers_2"⟩]
  bindingRefs := [⟨"workers"⟩]
  entries := []
  exits :=
    [ { node := ⟨"sink"⟩
      , port := ⟨"done"⟩
      , contract := ⟨"Done"⟩
      , label := .label ⟨"done"⟩
      , exclusiveGroup := none
      }
    ]
  connections :=
    [ { fromEndpoint := { node := ⟨"workers_0"⟩, port := some ⟨"workers_0"⟩ }
      , toEndpoint := { node := ⟨"__star:gather:b30635591d8b"⟩, port := some ⟨"workers_0"⟩ }
      }
    , { fromEndpoint := { node := ⟨"workers_1"⟩, port := some ⟨"workers_1"⟩ }
      , toEndpoint := { node := ⟨"__star:gather:b30635591d8b"⟩, port := some ⟨"workers_1"⟩ }
      }
    , { fromEndpoint := { node := ⟨"workers_2"⟩, port := some ⟨"workers_2"⟩ }
      , toEndpoint := { node := ⟨"__star:gather:b30635591d8b"⟩, port := some ⟨"workers_2"⟩ }
      }
    , { fromEndpoint := { node := ⟨"__star:gather:b30635591d8b"⟩, port := some ⟨"samples"⟩ }
      , toEndpoint := { node := ⟨"sink"⟩, port := some ⟨"samples"⟩ }
      }
    ]
  primitiveSteps :=
    [ .node
          ⟨"workers_0"⟩
          []
          [ { node := ⟨"workers_0"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"workers_1"⟩
          []
          [ { node := ⟨"workers_1"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          ]
    , .overlay [⟨"workers_0"⟩] [⟨"workers_1"⟩] [] []
    , .node
          ⟨"workers_2"⟩
          []
          [ { node := ⟨"workers_2"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
    , .overlay [⟨"workers_0"⟩, ⟨"workers_1"⟩] [⟨"workers_2"⟩] [] []
    , .bindingRef ⟨"workers"⟩
    , .node
          ⟨"__star:gather:b30635591d8b"⟩
          [ { node := ⟨"__star:gather:b30635591d8b"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:gather:b30635591d8b"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:gather:b30635591d8b"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"__star:gather:b30635591d8b"⟩
            , port := ⟨"samples"⟩
            , contract := ⟨"[Sample;3]"⟩
            , label := .label ⟨"samples"⟩
            , exclusiveGroup := none
            }
          ]
    , .connect
          [ { node := ⟨"workers_0"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"workers_1"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"workers_2"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"__star:gather:b30635591d8b"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:gather:b30635591d8b"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:gather:b30635591d8b"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"workers_0"⟩
                , port := ⟨"workers_0"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_0"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:gather:b30635591d8b"⟩
                , port := ⟨"workers_0"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_0"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"workers_1"⟩
                , port := ⟨"workers_1"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_1"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:gather:b30635591d8b"⟩
                , port := ⟨"workers_1"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_1"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"workers_2"⟩
                , port := ⟨"workers_2"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_2"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:gather:b30635591d8b"⟩
                , port := ⟨"workers_2"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_2"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    , .node
          ⟨"sink"⟩
          [ { node := ⟨"sink"⟩
            , port := ⟨"samples"⟩
            , contract := ⟨"[Sample;3]"⟩
            , label := .label ⟨"samples"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"sink"⟩
            , port := ⟨"done"⟩
            , contract := ⟨"Done"⟩
            , label := .label ⟨"done"⟩
            , exclusiveGroup := none
            }
          ]
    , .connect
          [ { node := ⟨"__star:gather:b30635591d8b"⟩
            , port := ⟨"samples"⟩
            , contract := ⟨"[Sample;3]"⟩
            , label := .label ⟨"samples"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"sink"⟩
            , port := ⟨"samples"⟩
            , contract := ⟨"[Sample;3]"⟩
            , label := .label ⟨"samples"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"__star:gather:b30635591d8b"⟩
                , port := ⟨"samples"⟩
                , contract := ⟨"[Sample;3]"⟩
                , label := .label ⟨"samples"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"sink"⟩
                , port := ⟨"samples"⟩
                , contract := ⟨"[Sample;3]"⟩
                , label := .label ⟨"samples"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    ]
  generatedForms :=
    [ { kind := .make
      , kindName := ⟨"sample"⟩
      , binding := ⟨"workers"⟩
      , sourceChildren :=
          [ { node := ⟨"workers_0"⟩, label := ⟨"0"⟩, value := none }
          , { node := ⟨"workers_1"⟩, label := ⟨"1"⟩, value := none }
          , { node := ⟨"workers_2"⟩, label := ⟨"2"⟩, value := none }
          ]
      , usedChildren :=
          [ { node := ⟨"workers_0"⟩
            , label := ⟨"0"⟩
            , outputs :=
                [ { node := ⟨"workers_0"⟩
                  , port := ⟨"workers_0"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_0"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs := []
            }
          , { node := ⟨"workers_1"⟩
            , label := ⟨"1"⟩
            , outputs :=
                [ { node := ⟨"workers_1"⟩
                  , port := ⟨"workers_1"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_1"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs := []
            }
          , { node := ⟨"workers_2"⟩
            , label := ⟨"2"⟩
            , outputs :=
                [ { node := ⟨"workers_2"⟩
                  , port := ⟨"workers_2"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_2"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs := []
            }
          ]
      }
    ]
  phantomAdapters :=
    [ { direction := .gather
      , node := ⟨"__star:gather:b30635591d8b"⟩
      , productShape := .indexed ⟨"Sample"⟩ 3
      , singular :=
          { node := ⟨"sink"⟩
          , port := ⟨"samples"⟩
          , contract := ⟨"[Sample;3]"⟩
          , label := .label ⟨"samples"⟩
          , exclusiveGroup := none
          }
      , multi :=
          [ { node := ⟨"workers_0"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"workers_1"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"workers_2"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
      , leftBulk :=
          [ { fromPort :=
                { node := ⟨"workers_0"⟩
                , port := ⟨"workers_0"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_0"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:gather:b30635591d8b"⟩
                , port := ⟨"workers_0"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_0"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"workers_1"⟩
                , port := ⟨"workers_1"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_1"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:gather:b30635591d8b"⟩
                , port := ⟨"workers_1"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_1"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"workers_2"⟩
                , port := ⟨"workers_2"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_2"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:gather:b30635591d8b"⟩
                , port := ⟨"workers_2"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_2"⟩
                , exclusiveGroup := none
                }
            }
          ]
      , rightBulk :=
          [ { fromPort :=
                { node := ⟨"__star:gather:b30635591d8b"⟩
                , port := ⟨"samples"⟩
                , contract := ⟨"[Sample;3]"⟩
                , label := .label ⟨"samples"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"sink"⟩
                , port := ⟨"samples"⟩
                , contract := ⟨"[Sample;3]"⟩
                , label := .label ⟨"samples"⟩
                , exclusiveGroup := none
                }
            }
          ]
      }
    ]
  selects := []

-- The Lean-owned executable validator accepts the emitted artifact.
#guard artifact.validatorReadyCheck

/-- The accepted artifact satisfies the proof-facing soundness contract. -/
theorem artifact_sound : artifact.Sound :=
  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)

end EmittedIndexedGather
end AdmissionArtifact
end Cortex.Wire
