import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck

/-!
## Overview

Wire admission artifact emitted by the Haskell compiler for the
`IndexedScatter` fixture: indexed-product phantom scatter (source * workers).

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current compiler output.
`validatorReadyCheck_soundness` lifts the build-time boolean check below to
`WireAdmissionArtifact.Sound` for this artifact.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace EmittedIndexedScatter

/-- Emitted admission artifact for the
indexed-product phantom scatter (source * workers) fixture. -/
def artifact : WireAdmissionArtifact where
  schemaVersion := 4
  closureMode := .openFragment
  nodes :=
    [⟨"__star:scatter:c7ce4a38c306"⟩, ⟨"source"⟩, ⟨"workers_0"⟩, ⟨"workers_1"⟩, ⟨"workers_2"⟩]
  bindingRefs := [⟨"workers"⟩]
  entries := []
  exits :=
    [ { node := ⟨"workers_0"⟩
      , port := ⟨"workers_0"⟩
      , contract := ⟨"Done"⟩
      , label := .label ⟨"workers_0"⟩
      , exclusiveGroup := none
      }
    , { node := ⟨"workers_1"⟩
      , port := ⟨"workers_1"⟩
      , contract := ⟨"Done"⟩
      , label := .label ⟨"workers_1"⟩
      , exclusiveGroup := none
      }
    , { node := ⟨"workers_2"⟩
      , port := ⟨"workers_2"⟩
      , contract := ⟨"Done"⟩
      , label := .label ⟨"workers_2"⟩
      , exclusiveGroup := none
      }
    ]
  connections :=
    [ { fromEndpoint := { node := ⟨"source"⟩, port := some ⟨"samples"⟩ }
      , toEndpoint := { node := ⟨"__star:scatter:c7ce4a38c306"⟩, port := some ⟨"samples"⟩ }
      }
    , { fromEndpoint := { node := ⟨"__star:scatter:c7ce4a38c306"⟩, port := some ⟨"workers_0"⟩ }
      , toEndpoint := { node := ⟨"workers_0"⟩, port := some ⟨"workers_0"⟩ }
      }
    , { fromEndpoint := { node := ⟨"__star:scatter:c7ce4a38c306"⟩, port := some ⟨"workers_1"⟩ }
      , toEndpoint := { node := ⟨"workers_1"⟩, port := some ⟨"workers_1"⟩ }
      }
    , { fromEndpoint := { node := ⟨"__star:scatter:c7ce4a38c306"⟩, port := some ⟨"workers_2"⟩ }
      , toEndpoint := { node := ⟨"workers_2"⟩, port := some ⟨"workers_2"⟩ }
      }
    ]
  primitiveSteps :=
    [ .node
          ⟨"source"⟩
          []
          [ { node := ⟨"source"⟩
            , port := ⟨"samples"⟩
            , contract := ⟨"[Sample;3]"⟩
            , label := .label ⟨"samples"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"__star:scatter:c7ce4a38c306"⟩
          [ { node := ⟨"__star:scatter:c7ce4a38c306"⟩
            , port := ⟨"samples"⟩
            , contract := ⟨"[Sample;3]"⟩
            , label := .label ⟨"samples"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"__star:scatter:c7ce4a38c306"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:scatter:c7ce4a38c306"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:scatter:c7ce4a38c306"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
    , .connect
          [ { node := ⟨"source"⟩
            , port := ⟨"samples"⟩
            , contract := ⟨"[Sample;3]"⟩
            , label := .label ⟨"samples"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"__star:scatter:c7ce4a38c306"⟩
            , port := ⟨"samples"⟩
            , contract := ⟨"[Sample;3]"⟩
            , label := .label ⟨"samples"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"source"⟩
                , port := ⟨"samples"⟩
                , contract := ⟨"[Sample;3]"⟩
                , label := .label ⟨"samples"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                , port := ⟨"samples"⟩
                , contract := ⟨"[Sample;3]"⟩
                , label := .label ⟨"samples"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    , .node
          ⟨"workers_0"⟩
          [ { node := ⟨"workers_0"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"workers_0"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Done"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"workers_1"⟩
          [ { node := ⟨"workers_1"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"workers_1"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Done"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          ]
    , .overlay [⟨"workers_0"⟩] [⟨"workers_1"⟩] [] []
    , .node
          ⟨"workers_2"⟩
          [ { node := ⟨"workers_2"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"workers_2"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Done"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
    , .overlay [⟨"workers_0"⟩, ⟨"workers_1"⟩] [⟨"workers_2"⟩] [] []
    , .bindingRef ⟨"workers"⟩
    , .connect
          [ { node := ⟨"__star:scatter:c7ce4a38c306"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:scatter:c7ce4a38c306"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:scatter:c7ce4a38c306"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"workers_0"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"workers_1"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"workers_2"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                , port := ⟨"workers_0"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_0"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"workers_0"⟩
                , port := ⟨"workers_0"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_0"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                , port := ⟨"workers_1"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_1"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"workers_1"⟩
                , port := ⟨"workers_1"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_1"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                , port := ⟨"workers_2"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_2"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"workers_2"⟩
                , port := ⟨"workers_2"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_2"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    ]
  generatedForms :=
    [ { kind := .make
      , kindName := ⟨"consume"⟩
      , binding := ⟨"workers"⟩
      , sourceChildren :=
          [ { node := ⟨"workers_0"⟩, label := ⟨"0"⟩, value := none }
          , { node := ⟨"workers_1"⟩, label := ⟨"1"⟩, value := none }
          , { node := ⟨"workers_2"⟩, label := ⟨"2"⟩, value := none }
          ]
      , usedChildren :=
          [ { node := ⟨"workers_0"⟩
            , label := ⟨"0"⟩
            , outputs :=
                [ { node := ⟨"workers_0"⟩
                  , port := ⟨"workers_0"⟩
                  , contract := ⟨"Done"⟩
                  , label := .label ⟨"workers_0"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs :=
                [ { node := ⟨"workers_0"⟩
                  , port := ⟨"workers_0"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_0"⟩
                  , exclusiveGroup := none
                  }
                ]
            }
          , { node := ⟨"workers_1"⟩
            , label := ⟨"1"⟩
            , outputs :=
                [ { node := ⟨"workers_1"⟩
                  , port := ⟨"workers_1"⟩
                  , contract := ⟨"Done"⟩
                  , label := .label ⟨"workers_1"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs :=
                [ { node := ⟨"workers_1"⟩
                  , port := ⟨"workers_1"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_1"⟩
                  , exclusiveGroup := none
                  }
                ]
            }
          , { node := ⟨"workers_2"⟩
            , label := ⟨"2"⟩
            , outputs :=
                [ { node := ⟨"workers_2"⟩
                  , port := ⟨"workers_2"⟩
                  , contract := ⟨"Done"⟩
                  , label := .label ⟨"workers_2"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs :=
                [ { node := ⟨"workers_2"⟩
                  , port := ⟨"workers_2"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_2"⟩
                  , exclusiveGroup := none
                  }
                ]
            }
          ]
      }
    ]
  phantomAdapters :=
    [ { direction := .scatter
      , node := ⟨"__star:scatter:c7ce4a38c306"⟩
      , productShape := .indexed ⟨"Sample"⟩ 3
      , singular :=
          { node := ⟨"source"⟩
          , port := ⟨"samples"⟩
          , contract := ⟨"[Sample;3]"⟩
          , label := .label ⟨"samples"⟩
          , exclusiveGroup := none
          }
      , multi :=
          [ { node := ⟨"workers_0"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"workers_1"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"workers_2"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
      , leftBulk :=
          [ { fromPort :=
                { node := ⟨"source"⟩
                , port := ⟨"samples"⟩
                , contract := ⟨"[Sample;3]"⟩
                , label := .label ⟨"samples"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                , port := ⟨"samples"⟩
                , contract := ⟨"[Sample;3]"⟩
                , label := .label ⟨"samples"⟩
                , exclusiveGroup := none
                }
            }
          ]
      , rightBulk :=
          [ { fromPort :=
                { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                , port := ⟨"workers_0"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_0"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"workers_0"⟩
                , port := ⟨"workers_0"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_0"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                , port := ⟨"workers_1"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_1"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"workers_1"⟩
                , port := ⟨"workers_1"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_1"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                , port := ⟨"workers_2"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_2"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"workers_2"⟩
                , port := ⟨"workers_2"⟩
                , contract := ⟨"Sample"⟩
                , label := .label ⟨"workers_2"⟩
                , exclusiveGroup := none
                }
            }
          ]
      }
    ]
  selects := []
  endpointUses :=
    { inputUses :=
        [ { port :=
              { node := ⟨"__star:scatter:c7ce4a38c306"⟩
              , port := ⟨"samples"⟩
              , contract := ⟨"[Sample;3]"⟩
              , label := .label ⟨"samples"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .producedByEdge
                  { node := ⟨"source"⟩
                  , port := ⟨"samples"⟩
                  , contract := ⟨"[Sample;3]"⟩
                  , label := .label ⟨"samples"⟩
                  , exclusiveGroup := none
                  }
          }
        , { port :=
              { node := ⟨"workers_0"⟩
              , port := ⟨"workers_0"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_0"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .producedByEdge
                  { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                  , port := ⟨"workers_0"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_0"⟩
                  , exclusiveGroup := none
                  }
          }
        , { port :=
              { node := ⟨"workers_1"⟩
              , port := ⟨"workers_1"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_1"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .producedByEdge
                  { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                  , port := ⟨"workers_1"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_1"⟩
                  , exclusiveGroup := none
                  }
          }
        , { port :=
              { node := ⟨"workers_2"⟩
              , port := ⟨"workers_2"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_2"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .producedByEdge
                  { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                  , port := ⟨"workers_2"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_2"⟩
                  , exclusiveGroup := none
                  }
          }
        ]
    , outputUses :=
        [ { port :=
              { node := ⟨"source"⟩
              , port := ⟨"samples"⟩
              , contract := ⟨"[Sample;3]"⟩
              , label := .label ⟨"samples"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .consumedByEdge
                  { node := ⟨"__star:scatter:c7ce4a38c306"⟩
                  , port := ⟨"samples"⟩
                  , contract := ⟨"[Sample;3]"⟩
                  , label := .label ⟨"samples"⟩
                  , exclusiveGroup := none
                  }
          }
        , { port :=
              { node := ⟨"__star:scatter:c7ce4a38c306"⟩
              , port := ⟨"workers_0"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_0"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .consumedByEdge
                  { node := ⟨"workers_0"⟩
                  , port := ⟨"workers_0"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_0"⟩
                  , exclusiveGroup := none
                  }
          }
        , { port :=
              { node := ⟨"__star:scatter:c7ce4a38c306"⟩
              , port := ⟨"workers_1"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_1"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .consumedByEdge
                  { node := ⟨"workers_1"⟩
                  , port := ⟨"workers_1"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_1"⟩
                  , exclusiveGroup := none
                  }
          }
        , { port :=
              { node := ⟨"__star:scatter:c7ce4a38c306"⟩
              , port := ⟨"workers_2"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_2"⟩
              , exclusiveGroup := none
              }
          , useKind :=
              .consumedByEdge
                  { node := ⟨"workers_2"⟩
                  , port := ⟨"workers_2"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_2"⟩
                  , exclusiveGroup := none
                  }
          }
        , { port :=
              { node := ⟨"workers_0"⟩
              , port := ⟨"workers_0"⟩
              , contract := ⟨"Done"⟩
              , label := .label ⟨"workers_0"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        , { port :=
              { node := ⟨"workers_1"⟩
              , port := ⟨"workers_1"⟩
              , contract := ⟨"Done"⟩
              , label := .label ⟨"workers_1"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        , { port :=
              { node := ⟨"workers_2"⟩
              , port := ⟨"workers_2"⟩
              , contract := ⟨"Done"⟩
              , label := .label ⟨"workers_2"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        ]
    }

-- The Lean-owned executable validator accepts the emitted artifact.
#guard artifact.validatorReadyCheck

/-- The accepted artifact satisfies the proof-facing soundness contract. -/
theorem artifact_sound : artifact.Sound :=
  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)

end EmittedIndexedScatter
end AdmissionArtifact
end Cortex.Wire
