import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck

/-!
## Overview

Wire admission artifact emitted by the Haskell compiler for the
`Make` fixture: bounded make expansion (make(3, sample)).

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current compiler output.
`validatorReadyCheck_soundness` lifts the build-time boolean check below to
`WireAdmissionArtifact.Sound` for this artifact.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace EmittedMake

/-- Emitted admission artifact for the bounded make expansion (make(3, sample)) fixture. -/
def artifact : WireAdmissionArtifact where
  schemaVersion := 4
  closureMode := .openFragment
  nodes := [⟨"workers_0"⟩, ⟨"workers_1"⟩, ⟨"workers_2"⟩]
  bindingRefs := [⟨"workers"⟩]
  entries := []
  exits :=
    [ { node := ⟨"workers_0"⟩
      , port := ⟨"workers_0"⟩
      , contract := ⟨"Sample"⟩
      , label := .label ⟨"workers_0"⟩
      , exclusiveGroup := none
      }
    , { node := ⟨"workers_1"⟩
      , port := ⟨"workers_1"⟩
      , contract := ⟨"Sample"⟩
      , label := .label ⟨"workers_1"⟩
      , exclusiveGroup := none
      }
    , { node := ⟨"workers_2"⟩
      , port := ⟨"workers_2"⟩
      , contract := ⟨"Sample"⟩
      , label := .label ⟨"workers_2"⟩
      , exclusiveGroup := none
      }
    ]
  connections := []
  primitiveSteps :=
    [ .node
          ⟨"workers_0"⟩
          []
          [ { node := ⟨"workers_0"⟩
            , port := ⟨"workers_0"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_0"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"workers_1"⟩
          []
          [ { node := ⟨"workers_1"⟩
            , port := ⟨"workers_1"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_1"⟩
            , exclusiveGroup := none
            }
          ]
    , .overlay [⟨"workers_0"⟩] [⟨"workers_1"⟩] [] []
    , .node
          ⟨"workers_2"⟩
          []
          [ { node := ⟨"workers_2"⟩
            , port := ⟨"workers_2"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_2"⟩
            , exclusiveGroup := none
            }
          ]
    , .overlay [⟨"workers_0"⟩, ⟨"workers_1"⟩] [⟨"workers_2"⟩] [] []
    , .bindingRef ⟨"workers"⟩
    ]
  generatedForms :=
    [ { kind := .make
      , kindName := ⟨"sample"⟩
      , binding := ⟨"workers"⟩
      , sourceChildren :=
          [ { node := ⟨"workers_0"⟩, label := ⟨"0"⟩, value := none }
          , { node := ⟨"workers_1"⟩, label := ⟨"1"⟩, value := none }
          , { node := ⟨"workers_2"⟩, label := ⟨"2"⟩, value := none }
          ]
      , usedChildren :=
          [ { node := ⟨"workers_0"⟩
            , label := ⟨"0"⟩
            , outputs :=
                [ { node := ⟨"workers_0"⟩
                  , port := ⟨"workers_0"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_0"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs := []
            }
          , { node := ⟨"workers_1"⟩
            , label := ⟨"1"⟩
            , outputs :=
                [ { node := ⟨"workers_1"⟩
                  , port := ⟨"workers_1"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_1"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs := []
            }
          , { node := ⟨"workers_2"⟩
            , label := ⟨"2"⟩
            , outputs :=
                [ { node := ⟨"workers_2"⟩
                  , port := ⟨"workers_2"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_2"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs := []
            }
          ]
      }
    ]
  phantomAdapters := []
  selects := []
  endpointUses :=
    { inputUses := []
    , outputUses :=
        [ { port :=
              { node := ⟨"workers_0"⟩
              , port := ⟨"workers_0"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_0"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        , { port :=
              { node := ⟨"workers_1"⟩
              , port := ⟨"workers_1"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_1"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        , { port :=
              { node := ⟨"workers_2"⟩
              , port := ⟨"workers_2"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_2"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        ]
    }

-- The Lean-owned executable validator accepts the emitted artifact.
#guard artifact.validatorReadyCheck

/-- The accepted artifact satisfies the proof-facing soundness contract. -/
theorem artifact_sound : artifact.Sound :=
  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)

end EmittedMake
end AdmissionArtifact
end Cortex.Wire
