import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck

/-!
## Overview

Wire admission artifact emitted by the Haskell compiler for the
`MakeEach` fixture: item-labeled makeEach expansion.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current compiler output.
`validatorReadyCheck_soundness` lifts the build-time boolean check below to
`WireAdmissionArtifact.Sound` for this artifact.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace EmittedMakeEach

/-- Emitted admission artifact for the item-labeled makeEach expansion fixture. -/
def artifact : WireAdmissionArtifact where
  schemaVersion := 4
  closureMode := .openFragment
  nodes := [⟨"workers_alpha"⟩, ⟨"workers_beta"⟩]
  bindingRefs := [⟨"workers"⟩]
  entries := []
  exits :=
    [ { node := ⟨"workers_alpha"⟩
      , port := ⟨"workers_alpha"⟩
      , contract := ⟨"Sample"⟩
      , label := .label ⟨"workers_alpha"⟩
      , exclusiveGroup := none
      }
    , { node := ⟨"workers_beta"⟩
      , port := ⟨"workers_beta"⟩
      , contract := ⟨"Sample"⟩
      , label := .label ⟨"workers_beta"⟩
      , exclusiveGroup := none
      }
    ]
  connections := []
  primitiveSteps :=
    [ .node
          ⟨"workers_alpha"⟩
          []
          [ { node := ⟨"workers_alpha"⟩
            , port := ⟨"workers_alpha"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_alpha"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"workers_beta"⟩
          []
          [ { node := ⟨"workers_beta"⟩
            , port := ⟨"workers_beta"⟩
            , contract := ⟨"Sample"⟩
            , label := .label ⟨"workers_beta"⟩
            , exclusiveGroup := none
            }
          ]
    , .overlay [⟨"workers_alpha"⟩] [⟨"workers_beta"⟩] [] []
    , .bindingRef ⟨"workers"⟩
    ]
  generatedForms :=
    [ { kind := .makeEach
      , kindName := ⟨"sample"⟩
      , binding := ⟨"workers"⟩
      , sourceChildren :=
          [ { node := ⟨"workers_alpha"⟩, label := ⟨"alpha"⟩, value := none }
          , { node := ⟨"workers_beta"⟩, label := ⟨"beta"⟩, value := none }
          ]
      , usedChildren :=
          [ { node := ⟨"workers_alpha"⟩
            , label := ⟨"alpha"⟩
            , outputs :=
                [ { node := ⟨"workers_alpha"⟩
                  , port := ⟨"workers_alpha"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_alpha"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs := []
            }
          , { node := ⟨"workers_beta"⟩
            , label := ⟨"beta"⟩
            , outputs :=
                [ { node := ⟨"workers_beta"⟩
                  , port := ⟨"workers_beta"⟩
                  , contract := ⟨"Sample"⟩
                  , label := .label ⟨"workers_beta"⟩
                  , exclusiveGroup := none
                  }
                ]
            , inputs := []
            }
          ]
      }
    ]
  phantomAdapters := []
  selects := []
  endpointUses :=
    { inputUses := []
    , outputUses :=
        [ { port :=
              { node := ⟨"workers_alpha"⟩
              , port := ⟨"workers_alpha"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_alpha"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        , { port :=
              { node := ⟨"workers_beta"⟩
              , port := ⟨"workers_beta"⟩
              , contract := ⟨"Sample"⟩
              , label := .label ⟨"workers_beta"⟩
              , exclusiveGroup := none
              }
          , useKind := .terminalDischarge .exportedBoundary
          }
        ]
    }

-- The Lean-owned executable validator accepts the emitted artifact.
#guard artifact.validatorReadyCheck

/-- The accepted artifact satisfies the proof-facing soundness contract. -/
theorem artifact_sound : artifact.Sound :=
  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)

end EmittedMakeEach
end AdmissionArtifact
end Cortex.Wire
