import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck

/-!
## Overview

Wire admission artifact emitted by the Haskell compiler for the
`RecordScatter` fixture: record-form phantom scatter (source * (a <> b)).

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current compiler output.
`validatorReadyCheck_soundness` lifts the build-time boolean check below to
`WireAdmissionArtifact.Sound` for this artifact.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace EmittedRecordScatter

/-- Emitted admission artifact for the
record-form phantom scatter (source * (a <> b)) fixture. -/
def artifact : WireAdmissionArtifact where
  schemaVersion := 3
  nodes := [⟨"__star:scatter:7dc42cd924f2"⟩, ⟨"a"⟩, ⟨"b"⟩, ⟨"source"⟩]
  bindingRefs := []
  entries := []
  exits :=
    [ { node := ⟨"a"⟩
      , port := ⟨"done_a"⟩
      , contract := ⟨"Done"⟩
      , label := .label ⟨"done_a"⟩
      , exclusiveGroup := none
      }
    , { node := ⟨"b"⟩
      , port := ⟨"done_b"⟩
      , contract := ⟨"Done"⟩
      , label := .label ⟨"done_b"⟩
      , exclusiveGroup := none
      }
    ]
  connections :=
    [ { fromEndpoint := { node := ⟨"source"⟩, port := some ⟨"pair"⟩ }
      , toEndpoint := { node := ⟨"__star:scatter:7dc42cd924f2"⟩, port := some ⟨"pair"⟩ }
      }
    , { fromEndpoint := { node := ⟨"__star:scatter:7dc42cd924f2"⟩, port := some ⟨"a"⟩ }
      , toEndpoint := { node := ⟨"a"⟩, port := some ⟨"a"⟩ }
      }
    , { fromEndpoint := { node := ⟨"__star:scatter:7dc42cd924f2"⟩, port := some ⟨"b"⟩ }
      , toEndpoint := { node := ⟨"b"⟩, port := some ⟨"b"⟩ }
      }
    ]
  primitiveSteps :=
    [ .node
          ⟨"source"⟩
          []
          [ { node := ⟨"source"⟩
            , port := ⟨"pair"⟩
            , contract := ⟨"Pair"⟩
            , label := .label ⟨"pair"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"__star:scatter:7dc42cd924f2"⟩
          [ { node := ⟨"__star:scatter:7dc42cd924f2"⟩
            , port := ⟨"pair"⟩
            , contract := ⟨"Pair"⟩
            , label := .label ⟨"pair"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"__star:scatter:7dc42cd924f2"⟩
            , port := ⟨"a"⟩
            , contract := ⟨"A"⟩
            , label := .label ⟨"a"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:scatter:7dc42cd924f2"⟩
            , port := ⟨"b"⟩
            , contract := ⟨"B"⟩
            , label := .label ⟨"b"⟩
            , exclusiveGroup := none
            }
          ]
    , .connect
          [ { node := ⟨"source"⟩
            , port := ⟨"pair"⟩
            , contract := ⟨"Pair"⟩
            , label := .label ⟨"pair"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"__star:scatter:7dc42cd924f2"⟩
            , port := ⟨"pair"⟩
            , contract := ⟨"Pair"⟩
            , label := .label ⟨"pair"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"source"⟩
                , port := ⟨"pair"⟩
                , contract := ⟨"Pair"⟩
                , label := .label ⟨"pair"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:scatter:7dc42cd924f2"⟩
                , port := ⟨"pair"⟩
                , contract := ⟨"Pair"⟩
                , label := .label ⟨"pair"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    , .node
          ⟨"a"⟩
          [ { node := ⟨"a"⟩
            , port := ⟨"a"⟩
            , contract := ⟨"A"⟩
            , label := .label ⟨"a"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"a"⟩
            , port := ⟨"done_a"⟩
            , contract := ⟨"Done"⟩
            , label := .label ⟨"done_a"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"b"⟩
          [ { node := ⟨"b"⟩
            , port := ⟨"b"⟩
            , contract := ⟨"B"⟩
            , label := .label ⟨"b"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"b"⟩
            , port := ⟨"done_b"⟩
            , contract := ⟨"Done"⟩
            , label := .label ⟨"done_b"⟩
            , exclusiveGroup := none
            }
          ]
    , .overlay [⟨"a"⟩] [⟨"b"⟩] [] []
    , .connect
          [ { node := ⟨"__star:scatter:7dc42cd924f2"⟩
            , port := ⟨"a"⟩
            , contract := ⟨"A"⟩
            , label := .label ⟨"a"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__star:scatter:7dc42cd924f2"⟩
            , port := ⟨"b"⟩
            , contract := ⟨"B"⟩
            , label := .label ⟨"b"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"a"⟩
            , port := ⟨"a"⟩
            , contract := ⟨"A"⟩
            , label := .label ⟨"a"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"b"⟩
            , port := ⟨"b"⟩
            , contract := ⟨"B"⟩
            , label := .label ⟨"b"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"__star:scatter:7dc42cd924f2"⟩
                , port := ⟨"a"⟩
                , contract := ⟨"A"⟩
                , label := .label ⟨"a"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"a"⟩
                , port := ⟨"a"⟩
                , contract := ⟨"A"⟩
                , label := .label ⟨"a"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"__star:scatter:7dc42cd924f2"⟩
                , port := ⟨"b"⟩
                , contract := ⟨"B"⟩
                , label := .label ⟨"b"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"b"⟩
                , port := ⟨"b"⟩
                , contract := ⟨"B"⟩
                , label := .label ⟨"b"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    ]
  generatedForms := []
  phantomAdapters :=
    [ { direction := .scatter
      , node := ⟨"__star:scatter:7dc42cd924f2"⟩
      , productShape := .record ⟨"Pair"⟩ [(⟨"a"⟩, ⟨"A"⟩), (⟨"b"⟩, ⟨"B"⟩)]
      , singular :=
          { node := ⟨"source"⟩
          , port := ⟨"pair"⟩
          , contract := ⟨"Pair"⟩
          , label := .label ⟨"pair"⟩
          , exclusiveGroup := none
          }
      , multi :=
          [ { node := ⟨"a"⟩
            , port := ⟨"a"⟩
            , contract := ⟨"A"⟩
            , label := .label ⟨"a"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"b"⟩
            , port := ⟨"b"⟩
            , contract := ⟨"B"⟩
            , label := .label ⟨"b"⟩
            , exclusiveGroup := none
            }
          ]
      , leftBulk :=
          [ { fromPort :=
                { node := ⟨"source"⟩
                , port := ⟨"pair"⟩
                , contract := ⟨"Pair"⟩
                , label := .label ⟨"pair"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"__star:scatter:7dc42cd924f2"⟩
                , port := ⟨"pair"⟩
                , contract := ⟨"Pair"⟩
                , label := .label ⟨"pair"⟩
                , exclusiveGroup := none
                }
            }
          ]
      , rightBulk :=
          [ { fromPort :=
                { node := ⟨"__star:scatter:7dc42cd924f2"⟩
                , port := ⟨"a"⟩
                , contract := ⟨"A"⟩
                , label := .label ⟨"a"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"a"⟩
                , port := ⟨"a"⟩
                , contract := ⟨"A"⟩
                , label := .label ⟨"a"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"__star:scatter:7dc42cd924f2"⟩
                , port := ⟨"b"⟩
                , contract := ⟨"B"⟩
                , label := .label ⟨"b"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"b"⟩
                , port := ⟨"b"⟩
                , contract := ⟨"B"⟩
                , label := .label ⟨"b"⟩
                , exclusiveGroup := none
                }
            }
          ]
      }
    ]
  selects := []

-- The Lean-owned executable validator accepts the emitted artifact.
#guard artifact.validatorReadyCheck

/-- The accepted artifact satisfies the proof-facing soundness contract. -/
theorem artifact_sound : artifact.Sound :=
  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)

end EmittedRecordScatter
end AdmissionArtifact
end Cortex.Wire
