import Cortex.Wire.AdmissionArtifact.ValidatorCoreCheck

/-!
## Overview

Wire admission artifact emitted by the Haskell compiler for the
`SelectLabel` fixture: label-resolved select with a non-identity arm.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current compiler output.
`validatorReadyCheck_soundness` lifts the build-time boolean check below to
`WireAdmissionArtifact.Sound` for this artifact.
-/

namespace Cortex.Wire
namespace AdmissionArtifact
namespace EmittedSelectLabel

/-- Emitted admission artifact for the label-resolved select with a non-identity arm fixture. -/
def artifact : WireAdmissionArtifact where
  schemaVersion := 3
  nodes :=
    [⟨"__select:ok_issue:4498bc399c9c"⟩, ⟨"draft_plan"⟩, ⟨"publish_report"⟩, ⟨"validate_plan"⟩]
  bindingRefs := []
  entries := []
  exits :=
    [ { node := ⟨"publish_report"⟩
      , port := ⟨"report"⟩
      , contract := ⟨"ReportArtifactRef"⟩
      , label := .label ⟨"report"⟩
      , exclusiveGroup := none
      }
    ]
  connections :=
    [ { fromEndpoint := { node := ⟨"draft_plan"⟩, port := some ⟨"draft"⟩ }
      , toEndpoint := { node := ⟨"validate_plan"⟩, port := some ⟨"draft"⟩ }
      }
    , { fromEndpoint := { node := ⟨"validate_plan"⟩, port := some ⟨"ok"⟩ }
      , toEndpoint :=
          { node := ⟨"__select:ok_issue:4498bc399c9c"⟩, port := some ⟨"variant_in_1"⟩ }
      }
    , { fromEndpoint := { node := ⟨"validate_plan"⟩, port := some ⟨"issue"⟩ }
      , toEndpoint :=
          { node := ⟨"__select:ok_issue:4498bc399c9c"⟩, port := some ⟨"variant_in_2"⟩ }
      }
    , { fromEndpoint :=
          { node := ⟨"__select:ok_issue:4498bc399c9c"⟩, port := some ⟨"bridge_out_1"⟩ }
      , toEndpoint := { node := ⟨"publish_report"⟩, port := some ⟨"ok"⟩ }
      }
    ]
  primitiveSteps :=
    [ .node
          ⟨"draft_plan"⟩
          []
          [ { node := ⟨"draft_plan"⟩
            , port := ⟨"draft"⟩
            , contract := ⟨"DraftPlan"⟩
            , label := .label ⟨"draft"⟩
            , exclusiveGroup := none
            }
          ]
    , .node
          ⟨"validate_plan"⟩
          [ { node := ⟨"validate_plan"⟩
            , port := ⟨"draft"⟩
            , contract := ⟨"DraftPlan"⟩
            , label := .label ⟨"draft"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"validate_plan"⟩
            , port := ⟨"ok"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := some (⟨"validate_plan"⟩, 0)
            }
          , { node := ⟨"validate_plan"⟩
            , port := ⟨"issue"⟩
            , contract := ⟨"PlanIssue"⟩
            , label := .label ⟨"issue"⟩
            , exclusiveGroup := some (⟨"validate_plan"⟩, 0)
            }
          ]
    , .connect
          [ { node := ⟨"draft_plan"⟩
            , port := ⟨"draft"⟩
            , contract := ⟨"DraftPlan"⟩
            , label := .label ⟨"draft"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"validate_plan"⟩
            , port := ⟨"draft"⟩
            , contract := ⟨"DraftPlan"⟩
            , label := .label ⟨"draft"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"draft_plan"⟩
                , port := ⟨"draft"⟩
                , contract := ⟨"DraftPlan"⟩
                , label := .label ⟨"draft"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"validate_plan"⟩
                , port := ⟨"draft"⟩
                , contract := ⟨"DraftPlan"⟩
                , label := .label ⟨"draft"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    , .node
          ⟨"__select:ok_issue:4498bc399c9c"⟩
          [ { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
            , port := ⟨"variant_in_1"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
            , port := ⟨"variant_in_2"⟩
            , contract := ⟨"PlanIssue"⟩
            , label := .label ⟨"issue"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
            , port := ⟨"variant_out_1"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := some (⟨"__select:ok_issue:4498bc399c9c"⟩, 0)
            }
          , { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
            , port := ⟨"variant_out_2"⟩
            , contract := ⟨"PlanIssue"⟩
            , label := .label ⟨"issue"⟩
            , exclusiveGroup := some (⟨"__select:ok_issue:4498bc399c9c"⟩, 0)
            }
          , { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
            , port := ⟨"bridge_out_1"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := none
            }
          ]
    , .connect
          [ { node := ⟨"validate_plan"⟩
            , port := ⟨"ok"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := some (⟨"validate_plan"⟩, 0)
            }
          , { node := ⟨"validate_plan"⟩
            , port := ⟨"issue"⟩
            , contract := ⟨"PlanIssue"⟩
            , label := .label ⟨"issue"⟩
            , exclusiveGroup := some (⟨"validate_plan"⟩, 0)
            }
          ]
          [ { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
            , port := ⟨"variant_in_1"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := none
            }
          , { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
            , port := ⟨"variant_in_2"⟩
            , contract := ⟨"PlanIssue"⟩
            , label := .label ⟨"issue"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"validate_plan"⟩
                , port := ⟨"ok"⟩
                , contract := ⟨"ResearchPlan"⟩
                , label := .label ⟨"ok"⟩
                , exclusiveGroup := some (⟨"validate_plan"⟩, 0)
                }
            , toPort :=
                { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
                , port := ⟨"variant_in_1"⟩
                , contract := ⟨"ResearchPlan"⟩
                , label := .label ⟨"ok"⟩
                , exclusiveGroup := none
                }
            }
          , { fromPort :=
                { node := ⟨"validate_plan"⟩
                , port := ⟨"issue"⟩
                , contract := ⟨"PlanIssue"⟩
                , label := .label ⟨"issue"⟩
                , exclusiveGroup := some (⟨"validate_plan"⟩, 0)
                }
            , toPort :=
                { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
                , port := ⟨"variant_in_2"⟩
                , contract := ⟨"PlanIssue"⟩
                , label := .label ⟨"issue"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    , .node
          ⟨"publish_report"⟩
          [ { node := ⟨"publish_report"⟩
            , port := ⟨"ok"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"publish_report"⟩
            , port := ⟨"report"⟩
            , contract := ⟨"ReportArtifactRef"⟩
            , label := .label ⟨"report"⟩
            , exclusiveGroup := none
            }
          ]
    , .connect
          [ { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
            , port := ⟨"bridge_out_1"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := none
            }
          ]
          [ { node := ⟨"publish_report"⟩
            , port := ⟨"ok"⟩
            , contract := ⟨"ResearchPlan"⟩
            , label := .label ⟨"ok"⟩
            , exclusiveGroup := none
            }
          ]
          [ { fromPort :=
                { node := ⟨"__select:ok_issue:4498bc399c9c"⟩
                , port := ⟨"bridge_out_1"⟩
                , contract := ⟨"ResearchPlan"⟩
                , label := .label ⟨"ok"⟩
                , exclusiveGroup := none
                }
            , toPort :=
                { node := ⟨"publish_report"⟩
                , port := ⟨"ok"⟩
                , contract := ⟨"ResearchPlan"⟩
                , label := .label ⟨"ok"⟩
                , exclusiveGroup := none
                }
            }
          ]
          []
          []
    ]
  generatedForms := []
  phantomAdapters := []
  selects :=
    [ { owner := ⟨"__select:ok_issue:4498bc399c9c"⟩
      , variants :=
          [ { key := ⟨"ok"⟩
            , port :=
                { node := ⟨"validate_plan"⟩
                , port := ⟨"ok"⟩
                , contract := ⟨"ResearchPlan"⟩
                , label := .label ⟨"ok"⟩
                , exclusiveGroup := some (⟨"validate_plan"⟩, 0)
                }
            }
          , { key := ⟨"issue"⟩
            , port :=
                { node := ⟨"validate_plan"⟩
                , port := ⟨"issue"⟩
                , contract := ⟨"PlanIssue"⟩
                , label := .label ⟨"issue"⟩
                , exclusiveGroup := some (⟨"validate_plan"⟩, 0)
                }
            }
          ]
      , arms :=
          [ { sourceIndex := 0
            , sourceKey := ⟨"ok"⟩
            , canonicalKey := ⟨"ok"⟩
            , mode := .resolvedByLabel
            , bodyNodes := []
            , bodyEntries := []
            , bodyExits := []
            }
          , { sourceIndex := 1
            , sourceKey := ⟨"issue"⟩
            , canonicalKey := ⟨"issue"⟩
            , mode := .resolvedByLabel
            , bodyNodes := [⟨"gather_missing_constraints"⟩, ⟨"repair_plan"⟩]
            , bodyEntries :=
                [ { node := ⟨"gather_missing_constraints"⟩
                  , port := ⟨"issue"⟩
                  , contract := ⟨"PlanIssue"⟩
                  , label := .label ⟨"issue"⟩
                  , exclusiveGroup := none
                  }
                ]
            , bodyExits :=
                [ { node := ⟨"repair_plan"⟩
                  , port := ⟨"ok"⟩
                  , contract := ⟨"ResearchPlan"⟩
                  , label := .label ⟨"ok"⟩
                  , exclusiveGroup := none
                  }
                ]
            }
          ]
      , conditionNode := ⟨"__select:ok_issue:4498bc399c9c"⟩
      }
    ]

-- The Lean-owned executable validator accepts the emitted artifact.
#guard artifact.validatorReadyCheck

/-- The accepted artifact satisfies the proof-facing soundness contract. -/
theorem artifact_sound : artifact.Sound :=
  WireAdmissionArtifact.validatorReadyCheck_soundness (by native_decide)

end EmittedSelectLabel
end AdmissionArtifact
end Cortex.Wire
