import Cortex.Wire.ContractValidationCheck

/-!
## Overview

Contract-schema dialect fixture for the
`AdditionalProperties` case: boolean additionalProperties rejecting undeclared keys.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current renderer output.
Acceptance theorems route through `schemaAcceptsCheck_sound`; rejection
theorems use the `Decidable` instance derived from completeness. Every
payload also carries a `#guard` for `Json.canonicalCheck`, the
canonical-form invariant structural equality relies on.
-/

namespace Cortex.Wire
namespace ContractValidation
namespace EmittedAdditionalProperties

/-- Parsed dialect schema for this fixture. -/
def schema : SchemaNode :=
  SchemaNode.mk
      ["object"]
      none
      []
      [("a", SchemaNode.mk ["string"] none [] [] none none none none none none)]
      (some false)
      none
      none
      none
      none
      none

/-- Payload the schema accepts. -/
def accepted0 : Json :=
  Json.obj [("a", Json.str "x")]

/-- Payload the schema rejects. -/
def rejected0 : Json :=
  Json.obj [("a", Json.str "x"), ("b", Json.num (mkRat 1 1))]

#guard (accepted0).canonicalCheck
#guard (rejected0).canonicalCheck
#guard schemaAcceptsCheck schema accepted0
#guard !(schemaAcceptsCheck schema rejected0)

/-- Accepted payload 0 satisfies the schema. -/
theorem accepted0_accepts : SchemaAccepts schema accepted0 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Rejected payload 0 violates the schema. -/
theorem rejected0_rejects : ¬ SchemaAccepts schema rejected0 := by
  native_decide

end EmittedAdditionalProperties
end ContractValidation
end Cortex.Wire
