import Cortex.Wire.ContractValidationCheck

/-!
## Overview

Contract-schema dialect fixture for the
`BoundsVacuity` case: string and number bounds constraining only their own payload kinds.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current renderer output.
Acceptance theorems route through `schemaAcceptsCheck_sound`; rejection
theorems use the `Decidable` instance derived from completeness. Every
payload also carries a `#guard` for `Json.canonicalCheck`, the
canonical-form invariant structural equality relies on.
-/

namespace Cortex.Wire
namespace ContractValidation
namespace EmittedBoundsVacuity

/-- Parsed dialect schema for this fixture. -/
def schema : SchemaNode :=
  SchemaNode.mk
      []
      none
      []
      []
      none
      none
      (some 5)
      (some 5)
      (some (mkRat 100 1))
      (some (mkRat 100 1))

/-- Payload the schema accepts. -/
def accepted0 : Json :=
  Json.bool true

/-- Payload the schema accepts. -/
def accepted1 : Json :=
  Json.null

/-- Payload the schema accepts. -/
def accepted2 : Json :=
  Json.obj []

/-- Payload the schema accepts. -/
def accepted3 : Json :=
  Json.str "12345"

/-- Payload the schema accepts. -/
def accepted4 : Json :=
  Json.num (mkRat 100 1)

/-- Payload the schema rejects. -/
def rejected0 : Json :=
  Json.str "1234"

/-- Payload the schema rejects. -/
def rejected1 : Json :=
  Json.num (mkRat 99 1)

#guard (accepted0).canonicalCheck
#guard (accepted1).canonicalCheck
#guard (accepted2).canonicalCheck
#guard (accepted3).canonicalCheck
#guard (accepted4).canonicalCheck
#guard (rejected0).canonicalCheck
#guard (rejected1).canonicalCheck
#guard schemaAcceptsCheck schema accepted0
#guard schemaAcceptsCheck schema accepted1
#guard schemaAcceptsCheck schema accepted2
#guard schemaAcceptsCheck schema accepted3
#guard schemaAcceptsCheck schema accepted4
#guard !(schemaAcceptsCheck schema rejected0)
#guard !(schemaAcceptsCheck schema rejected1)

/-- Accepted payload 0 satisfies the schema. -/
theorem accepted0_accepts : SchemaAccepts schema accepted0 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Accepted payload 1 satisfies the schema. -/
theorem accepted1_accepts : SchemaAccepts schema accepted1 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Accepted payload 2 satisfies the schema. -/
theorem accepted2_accepts : SchemaAccepts schema accepted2 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Accepted payload 3 satisfies the schema. -/
theorem accepted3_accepts : SchemaAccepts schema accepted3 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Accepted payload 4 satisfies the schema. -/
theorem accepted4_accepts : SchemaAccepts schema accepted4 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Rejected payload 0 violates the schema. -/
theorem rejected0_rejects : ¬ SchemaAccepts schema rejected0 := by
  native_decide

/-- Rejected payload 1 violates the schema. -/
theorem rejected1_rejects : ¬ SchemaAccepts schema rejected1 := by
  native_decide

end EmittedBoundsVacuity
end ContractValidation
end Cortex.Wire
