import Cortex.Wire.ContractValidationCheck

/-!
## Overview

Contract-schema dialect fixture for the
`EmptyEnum` case: an empty enum rejecting every payload.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current renderer output.
Acceptance theorems route through `schemaAcceptsCheck_sound`; rejection
theorems use the `Decidable` instance derived from completeness. Every
payload also carries a `#guard` for `Json.canonicalCheck`, the
canonical-form invariant structural equality relies on.
-/

namespace Cortex.Wire
namespace ContractValidation
namespace EmittedEmptyEnum

/-- Parsed dialect schema for this fixture. -/
def schema : SchemaNode :=
  SchemaNode.mk [] (some []) [] [] none none none none none none

/-- Payload the schema rejects. -/
def rejected0 : Json :=
  Json.null

/-- Payload the schema rejects. -/
def rejected1 : Json :=
  Json.str "x"

#guard (rejected0).canonicalCheck
#guard (rejected1).canonicalCheck
#guard !(schemaAcceptsCheck schema rejected0)
#guard !(schemaAcceptsCheck schema rejected1)

/-- Rejected payload 0 violates the schema. -/
theorem rejected0_rejects : ¬ SchemaAccepts schema rejected0 := by
  native_decide

/-- Rejected payload 1 violates the schema. -/
theorem rejected1_rejects : ¬ SchemaAccepts schema rejected1 := by
  native_decide

end EmittedEmptyEnum
end ContractValidation
end Cortex.Wire
