import Cortex.Wire.ContractValidationCheck

/-!
## Overview

Contract-schema dialect fixture for the
`ItemsVacuity` case: items constraining only array payloads.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current renderer output.
Acceptance theorems route through `schemaAcceptsCheck_sound`; rejection
theorems use the `Decidable` instance derived from completeness. Every
payload also carries a `#guard` for `Json.canonicalCheck`, the
canonical-form invariant structural equality relies on.
-/

namespace Cortex.Wire
namespace ContractValidation
namespace EmittedItemsVacuity

/-- Parsed dialect schema for this fixture. -/
def schema : SchemaNode :=
  SchemaNode.mk
      []
      none
      []
      []
      none
      (some (SchemaNode.mk ["string"] none [] [] none none none none none none))
      none
      none
      none
      none

/-- Payload the schema accepts. -/
def accepted0 : Json :=
  Json.num (mkRat 3 1)

/-- Payload the schema accepts. -/
def accepted1 : Json :=
  Json.obj []

/-- Payload the schema accepts. -/
def accepted2 : Json :=
  Json.arr [Json.str "a"]

/-- Payload the schema rejects. -/
def rejected0 : Json :=
  Json.arr [Json.num (mkRat 1 1)]

#guard (accepted0).canonicalCheck
#guard (accepted1).canonicalCheck
#guard (accepted2).canonicalCheck
#guard (rejected0).canonicalCheck
#guard schemaAcceptsCheck schema accepted0
#guard schemaAcceptsCheck schema accepted1
#guard schemaAcceptsCheck schema accepted2
#guard !(schemaAcceptsCheck schema rejected0)

/-- Accepted payload 0 satisfies the schema. -/
theorem accepted0_accepts : SchemaAccepts schema accepted0 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Accepted payload 1 satisfies the schema. -/
theorem accepted1_accepts : SchemaAccepts schema accepted1 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Accepted payload 2 satisfies the schema. -/
theorem accepted2_accepts : SchemaAccepts schema accepted2 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Rejected payload 0 violates the schema. -/
theorem rejected0_rejects : ¬ SchemaAccepts schema rejected0 := by
  native_decide

end EmittedItemsVacuity
end ContractValidation
end Cortex.Wire
