import Cortex.Wire.ContractValidationCheck

/-!
## Overview

Contract-schema dialect fixture for the
`SubsetAccept` case: the full supported-subset search schema.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current renderer output.
Acceptance theorems route through `schemaAcceptsCheck_sound`; rejection
theorems use the `Decidable` instance derived from completeness. Every
payload also carries a `#guard` for `Json.canonicalCheck`, the
canonical-form invariant structural equality relies on.
-/

namespace Cortex.Wire
namespace ContractValidation
namespace EmittedSubsetAccept

/-- Parsed dialect schema for this fixture. -/
def schema : SchemaNode :=
  SchemaNode.mk
      ["object"]
      none
      ["query", "filters", "tags"]
      [ ( "category"
        , SchemaNode.mk
              ["string"]
              (some [Json.str "news", Json.str "filings"])
              []
              []
              none
              none
              none
              none
              none
              none
        )
      , ( "filters"
        , SchemaNode.mk
              ["object"]
              none
              ["region"]
              [("region", SchemaNode.mk ["string"] none [] [] none none none none none none)]
              (some false)
              none
              none
              none
              none
              none
        )
      , ( "limit"
        , SchemaNode.mk
              ["integer"]
              none
              []
              []
              none
              none
              none
              none
              (some (mkRat 1 1))
              (some (mkRat 100 1))
        )
      , ("query", SchemaNode.mk ["string"] none [] [] none none (some 1) (some 40) none none)
      , ( "tags"
        , SchemaNode.mk
              ["array"]
              none
              []
              []
              none
              (some (SchemaNode.mk ["string"] none [] [] none none (some 1) none none none))
              none
              none
              none
              none
        )
      ]
      (some false)
      none
      none
      none
      none
      none

/-- Payload the schema accepts. -/
def accepted0 : Json :=
  Json.obj
      [ ("category", Json.str "filings")
      , ("filters", Json.obj [("region", Json.str "us")])
      , ("limit", Json.num (mkRat 10 1))
      , ("query", Json.str "amd")
      , ("tags", Json.arr [Json.str "filing", Json.str "earnings"])
      ]

/-- Payload the schema rejects. -/
def rejected0 : Json :=
  Json.obj [("query", Json.str "amd"), ("tags", Json.arr [Json.str "filing"])]

#guard (accepted0).canonicalCheck
#guard (rejected0).canonicalCheck
#guard schemaAcceptsCheck schema accepted0
#guard !(schemaAcceptsCheck schema rejected0)

/-- Accepted payload 0 satisfies the schema. -/
theorem accepted0_accepts : SchemaAccepts schema accepted0 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Rejected payload 0 violates the schema. -/
theorem rejected0_rejects : ¬ SchemaAccepts schema rejected0 := by
  native_decide

end EmittedSubsetAccept
end ContractValidation
end Cortex.Wire
