import Cortex.Wire.ContractValidationCheck

/-!
## Overview

Contract-schema dialect fixture for the
`TypeUnion` case: type unions admitting any member; unknown names admit nothing.

GENERATED FILE - do not edit by hand. Regenerated by
`just wire-lean-fixtures` from `Cortex.Wire.LeanFixture`; the Haskell test
suite fails when this file drifts from the current renderer output.
Acceptance theorems route through `schemaAcceptsCheck_sound`; rejection
theorems use the `Decidable` instance derived from completeness. Every
payload also carries a `#guard` for `Json.canonicalCheck`, the
canonical-form invariant structural equality relies on.
-/

namespace Cortex.Wire
namespace ContractValidation
namespace EmittedTypeUnion

/-- Parsed dialect schema for this fixture. -/
def schema : SchemaNode :=
  SchemaNode.mk ["string", "null", "mystery"] none [] [] none none none none none none

/-- Payload the schema accepts. -/
def accepted0 : Json :=
  Json.str "ok"

/-- Payload the schema accepts. -/
def accepted1 : Json :=
  Json.null

/-- Payload the schema rejects. -/
def rejected0 : Json :=
  Json.bool true

#guard (accepted0).canonicalCheck
#guard (accepted1).canonicalCheck
#guard (rejected0).canonicalCheck
#guard schemaAcceptsCheck schema accepted0
#guard schemaAcceptsCheck schema accepted1
#guard !(schemaAcceptsCheck schema rejected0)

/-- Accepted payload 0 satisfies the schema. -/
theorem accepted0_accepts : SchemaAccepts schema accepted0 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Accepted payload 1 satisfies the schema. -/
theorem accepted1_accepts : SchemaAccepts schema accepted1 :=
  schemaAcceptsCheck_sound (by native_decide)

/-- Rejected payload 0 violates the schema. -/
theorem rejected0_rejects : ¬ SchemaAccepts schema rejected0 := by
  native_decide

end EmittedTypeUnion
end ContractValidation
end Cortex.Wire
